export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_USER = 'SET_USER';
export const ADD_COMMENT = 'ADD_COMMENT';
export const SET_CURRENT_ACT = 'SET_CURRENT_ACT';
export const CLEAR_CURRENT_ACT = 'CLEAR_CURRENT_ACT';
export const SET_PUBLISH_ACT_COMMON = 'SET_PUBLISH_ACT_COMMON';
export const SET_PUBLISH_ACT_DETAIL = 'SET_PUBLISH_ACT_DETAIL';
export const SET_PUBLISH_TAXI_DEPART = 'SET_PUBLISH_TAXI_DEPART';
export const SET_PUBLISH_TAXI_ORIGIN = 'SET_PUBLISH_TAXI_ORIGIN';
export const SET_PUBLISH_TAXI_DEST = 'SET_PUBLISH_TAXI_DEST';
export const SET_PUBLISH_TAKEOUT_TIME = 'SET_PUBLISH_TAKEOUT_TIME';
export const SET_PUBLISH_TAKEOUT_STORE = 'SET_PUBLISH_TAKEOUT_STORE';
export const SET_PUBLISH_ACTIVITY_TIME = 'SET_PUBLISH_ACTIVITY_TIME';
export const SET_PUBLISH_ORDER_STORE = 'SET_PUBLISH_ORDER_STORE';
export const ADD_XMPP_MESSAGE = 'ADD_XMPP_MESSAGE';
export const INIT_XMPP_CHATROOMLIST = 'INIT_XMPP_CHATROOMLIST';

