export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_USER = 'SET_USER';
export const ADD_COMMENT = 'ADD_COMMENT';
export const SET_CURRENT_ACT = 'SET_CURRENT_ACT';
export const CLEAR_CURRENT_ACT = 'CLEAR_CURRENT_ACT';
export const SET_PUBLISH_ACT_COMMON = 'SET_PUBLISH_ACT_COMMON';
export const SET_PUBLISH_ACT_DETAIL = 'SET_PUBLISH_ACT_DETAIL';
export const SET_PUBLISH_TAXI_DEPART = 'SET_PUBLISH_TAXI_DEPART';
export const SET_PUBLISH_TAXI_ORIGIN = 'SET_PUBLISH_TAXI_ORIGIN';
export const SET_PUBLISH_TAXI_DEST = 'SET_PUBLISH_TAXI_DEST';
export const SET_PUBLISH_TAKEOUT_TIME = 'SET_PUBLISH_TAKEOUT_TIME';
export const SET_PUBLISH_TAKEOUT_STORE = 'SET_PUBLISH_TAKEOUT_STORE';
export const SET_PUBLISH_ACTIVITY_TIME = 'SET_PUBLISH_ACTIVITY_TIME';
export const SET_PUBLISH_ORDER_STORE = 'SET_PUBLISH_ORDER_STORE';
export const ADD_XMPP_MESSAGE = 'ADD_XMPP_MESSAGE';
export const INIT_XMPP_CHATROOMLIST = 'INIT_XMPP_CHATROOMLIST';


export const ON_NATIVE_LOGIN = 'ON_NATIVE_LOGIN';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_OK = 'LOGIN_OK';
export const GET_STATUS_FAIL = 'GET_STATUS_FAIL';

export const ON_LOADING_ACT_DETAIL = 'ON_LOADING_ACT_DETAIL';
export const LOAD_ACT_DETAIL_FAIL = 'LOAD_ACT_DETAIL_FAIL';
export const LOAD_ACT_DETAIL_OK = 'LOAD_ACT_DETAIL_OK';
export const ADD_COMMENT_OK = 'ADD_COMMENT_OK';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';

export const ON_LOADING_RECOMMEND = 'ON_LOADING_RECOMMEND';
export const LOADING_RECOMMEND_OK = 'LOADING_RECOMMEND_FAIL';
export const LOADING_RECOMMEND_FAIL = 'LOADING_RECOMMEND_FAIL';

export const ON_LOADING_FOLLOW = 'ON_LOADING_FOLLOW';
export const LOADING_FOLLOW_OK = 'LOADING_FOLLOW_OK';
export const LOADING_FOLLOW_FAIL = 'LOADING_FOLLOW_FAIL';

export const ON_LOADING_MY = 'ON_LOADING_MY';
export const LOADING_MY_OK = 'LOADING_MY_OK';
export const LOADING_MY_FAIL = 'LOADING_MY_FAIL';

export const ON_LOADING_TYPE = 'ON_LOADING_TYPE';
export const LOADING_TYPE_OK = 'LOADING_TYPE_OK';
export const LOADING_TYPE_FAIL = 'LOADING_TYPE_FAIL';

export const ON_SEND_MESSAGE = 'ON_SEND_MESSAGE';
export const ADD_CHAT_ROOM = 'ADD_CHAT_ROOM';
export const CHAT_ROOM_LOADED = 'CHAT_ROOM_LOADED';
export const ON_LOADING_CHAT_ROOM = 'ON_LOADING_CHAT_ROOM';
export const PRESENCE_CHAT_ROOM = 'PRESENT_CHAT_ROOM';

export const LOAD_PUBLISH_OK = 'LOAD_PUBLISH_OK';
export const LOAD_PUBLISH_FAIL = 'LOAD_PUBLISH_fAIL';


// follow action
export const ON_FOLLOW = 'ON_FOLLOW';
export const FOLLOW_OK = 'FOLLOW_OK';
export const FOLLOW_FAIL = 'FOLLOW_FAIL';

export const ON_UNFOLLOW = 'ON_UNFOLLOW';
export const UNFOLLOW_OK = 'UNFOLLOW_OK';
export const UNFOLLOW_FAIL = 'UNFOLLOW_FAIL';
export const ON_GET_FOLLOWINGS = 'ON_GET_FOLLOWING';
export const ON_GET_FOLLOWERS = 'ON_GET_FOLLOWERS';
export const GET_FOLLOWINGS_OK = 'GET_FOLLOWINGS_OK';
export const GET_FOLLOWINGS_FAIL = 'GET_FOLLOWERS_FAIL';
export const GET_FOLLOWERS_OK = 'GET_FOLLOWERS_OK';
export const GET_FOLLOWERS_FAIL = 'GET_FOLLOWERS_OK';
