export default {
    BACKGROUND_GREY: "#eeeeee",
    WHITE: "#fff",
    TEXT_BLACK: "#2c2c2c",
    TEXT_GREY: "#bfbfbf",
    TITLE_BLACK: "#1a1a1a",
    DEEP_BLUE: "#0077ff",
    PRIMARY_BLUE: "#0084ff",
    SECONDARY_BLUE: "#0e8afc",
    SOFT_BLUE: "#c0d2fc",
    DISABLED_GREY: "#cfcfcf",
    SUCCESS: "#67C23A",
    ERROR : "#F56C6C",
    WARNING: "#E6A23C",
    BUTTON_GREY: "#bbbbbb",
    TEXT_BUTTON_ENABLED: "#0084ff",
    TEXT_BUTTON_DISABLED: "#c0d2fc",
}
