############################################################
# Dockerfile to build login container images
############################################################
# Set the base image to Ubuntu
FROM ubuntu
# Add app to the image
ADD ./login /home/app/bin
# Run APP
RUN /home/app/bin/login