// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/activity.proto

package activity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BasicInfo struct {
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	CreateTime           string   `protobuf:"bytes,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	EndTime              string   `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Tag                  []string `protobuf:"bytes,7,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicInfo) Reset()         { *m = BasicInfo{} }
func (m *BasicInfo) String() string { return proto.CompactTextString(m) }
func (*BasicInfo) ProtoMessage()    {}
func (*BasicInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{0}
}

func (m *BasicInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicInfo.Unmarshal(m, b)
}
func (m *BasicInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicInfo.Marshal(b, m, deterministic)
}
func (m *BasicInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicInfo.Merge(m, src)
}
func (m *BasicInfo) XXX_Size() int {
	return xxx_messageInfo_BasicInfo.Size(m)
}
func (m *BasicInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BasicInfo proto.InternalMessageInfo

func (m *BasicInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *BasicInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *BasicInfo) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *BasicInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BasicInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BasicInfo) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

type PubReq struct {
	Info                 *BasicInfo   `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	TaxiInfo             *TaxiInfo    `protobuf:"bytes,4,opt,name=taxiInfo,proto3" json:"taxiInfo,omitempty"`
	TakeoutInfo          *TakeoutInfo `protobuf:"bytes,5,opt,name=takeoutInfo,proto3" json:"takeoutInfo,omitempty"`
	OrderInfo            *OrderInfo   `protobuf:"bytes,6,opt,name=orderInfo,proto3" json:"orderInfo,omitempty"`
	OtherInfo            *OtherInfo   `protobuf:"bytes,7,opt,name=otherInfo,proto3" json:"otherInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PubReq) Reset()         { *m = PubReq{} }
func (m *PubReq) String() string { return proto.CompactTextString(m) }
func (*PubReq) ProtoMessage()    {}
func (*PubReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{1}
}

func (m *PubReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubReq.Unmarshal(m, b)
}
func (m *PubReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubReq.Marshal(b, m, deterministic)
}
func (m *PubReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubReq.Merge(m, src)
}
func (m *PubReq) XXX_Size() int {
	return xxx_messageInfo_PubReq.Size(m)
}
func (m *PubReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PubReq.DiscardUnknown(m)
}

var xxx_messageInfo_PubReq proto.InternalMessageInfo

func (m *PubReq) GetInfo() *BasicInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *PubReq) GetTaxiInfo() *TaxiInfo {
	if m != nil {
		return m.TaxiInfo
	}
	return nil
}

func (m *PubReq) GetTakeoutInfo() *TakeoutInfo {
	if m != nil {
		return m.TakeoutInfo
	}
	return nil
}

func (m *PubReq) GetOrderInfo() *OrderInfo {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

func (m *PubReq) GetOtherInfo() *OtherInfo {
	if m != nil {
		return m.OtherInfo
	}
	return nil
}

type PubResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ActId                int32    `protobuf:"varint,3,opt,name=actId,proto3" json:"actId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubResp) Reset()         { *m = PubResp{} }
func (m *PubResp) String() string { return proto.CompactTextString(m) }
func (*PubResp) ProtoMessage()    {}
func (*PubResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{2}
}

func (m *PubResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubResp.Unmarshal(m, b)
}
func (m *PubResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubResp.Marshal(b, m, deterministic)
}
func (m *PubResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubResp.Merge(m, src)
}
func (m *PubResp) XXX_Size() int {
	return xxx_messageInfo_PubResp.Size(m)
}
func (m *PubResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PubResp.DiscardUnknown(m)
}

var xxx_messageInfo_PubResp proto.InternalMessageInfo

func (m *PubResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PubResp) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PubResp) GetActId() int32 {
	if m != nil {
		return m.ActId
	}
	return 0
}

type MdfReq struct {
	ActId                int32        `protobuf:"varint,1,opt,name=actId,proto3" json:"actId,omitempty"`
	CreateTime           string       `protobuf:"bytes,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	EndTime              string       `protobuf:"bytes,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Description          string       `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tag                  []string     `protobuf:"bytes,5,rep,name=tag,proto3" json:"tag,omitempty"`
	TaxiInfo             *TaxiInfo    `protobuf:"bytes,6,opt,name=taxiInfo,proto3" json:"taxiInfo,omitempty"`
	TakeoutInfo          *TakeoutInfo `protobuf:"bytes,7,opt,name=takeoutInfo,proto3" json:"takeoutInfo,omitempty"`
	OrderInfo            *OrderInfo   `protobuf:"bytes,8,opt,name=orderInfo,proto3" json:"orderInfo,omitempty"`
	OtherInfo            *OtherInfo   `protobuf:"bytes,9,opt,name=otherInfo,proto3" json:"otherInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MdfReq) Reset()         { *m = MdfReq{} }
func (m *MdfReq) String() string { return proto.CompactTextString(m) }
func (*MdfReq) ProtoMessage()    {}
func (*MdfReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{3}
}

func (m *MdfReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MdfReq.Unmarshal(m, b)
}
func (m *MdfReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MdfReq.Marshal(b, m, deterministic)
}
func (m *MdfReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MdfReq.Merge(m, src)
}
func (m *MdfReq) XXX_Size() int {
	return xxx_messageInfo_MdfReq.Size(m)
}
func (m *MdfReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MdfReq.DiscardUnknown(m)
}

var xxx_messageInfo_MdfReq proto.InternalMessageInfo

func (m *MdfReq) GetActId() int32 {
	if m != nil {
		return m.ActId
	}
	return 0
}

func (m *MdfReq) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *MdfReq) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *MdfReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MdfReq) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *MdfReq) GetTaxiInfo() *TaxiInfo {
	if m != nil {
		return m.TaxiInfo
	}
	return nil
}

func (m *MdfReq) GetTakeoutInfo() *TakeoutInfo {
	if m != nil {
		return m.TakeoutInfo
	}
	return nil
}

func (m *MdfReq) GetOrderInfo() *OrderInfo {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

func (m *MdfReq) GetOtherInfo() *OtherInfo {
	if m != nil {
		return m.OtherInfo
	}
	return nil
}

type MdfResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MdfResp) Reset()         { *m = MdfResp{} }
func (m *MdfResp) String() string { return proto.CompactTextString(m) }
func (*MdfResp) ProtoMessage()    {}
func (*MdfResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{4}
}

func (m *MdfResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MdfResp.Unmarshal(m, b)
}
func (m *MdfResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MdfResp.Marshal(b, m, deterministic)
}
func (m *MdfResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MdfResp.Merge(m, src)
}
func (m *MdfResp) XXX_Size() int {
	return xxx_messageInfo_MdfResp.Size(m)
}
func (m *MdfResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MdfResp.DiscardUnknown(m)
}

var xxx_messageInfo_MdfResp proto.InternalMessageInfo

func (m *MdfResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MdfResp) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type DltReq struct {
	ActId                int32    `protobuf:"varint,1,opt,name=actId,proto3" json:"actId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DltReq) Reset()         { *m = DltReq{} }
func (m *DltReq) String() string { return proto.CompactTextString(m) }
func (*DltReq) ProtoMessage()    {}
func (*DltReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{5}
}

func (m *DltReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DltReq.Unmarshal(m, b)
}
func (m *DltReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DltReq.Marshal(b, m, deterministic)
}
func (m *DltReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DltReq.Merge(m, src)
}
func (m *DltReq) XXX_Size() int {
	return xxx_messageInfo_DltReq.Size(m)
}
func (m *DltReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DltReq.DiscardUnknown(m)
}

var xxx_messageInfo_DltReq proto.InternalMessageInfo

func (m *DltReq) GetActId() int32 {
	if m != nil {
		return m.ActId
	}
	return 0
}

type DltResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DltResp) Reset()         { *m = DltResp{} }
func (m *DltResp) String() string { return proto.CompactTextString(m) }
func (*DltResp) ProtoMessage()    {}
func (*DltResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{6}
}

func (m *DltResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DltResp.Unmarshal(m, b)
}
func (m *DltResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DltResp.Marshal(b, m, deterministic)
}
func (m *DltResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DltResp.Merge(m, src)
}
func (m *DltResp) XXX_Size() int {
	return xxx_messageInfo_DltResp.Size(m)
}
func (m *DltResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DltResp.DiscardUnknown(m)
}

var xxx_messageInfo_DltResp proto.InternalMessageInfo

func (m *DltResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DltResp) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type QryReq struct {
	ActId                int32    `protobuf:"varint,1,opt,name=actId,proto3" json:"actId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QryReq) Reset()         { *m = QryReq{} }
func (m *QryReq) String() string { return proto.CompactTextString(m) }
func (*QryReq) ProtoMessage()    {}
func (*QryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{7}
}

func (m *QryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QryReq.Unmarshal(m, b)
}
func (m *QryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QryReq.Marshal(b, m, deterministic)
}
func (m *QryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QryReq.Merge(m, src)
}
func (m *QryReq) XXX_Size() int {
	return xxx_messageInfo_QryReq.Size(m)
}
func (m *QryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QryReq.DiscardUnknown(m)
}

var xxx_messageInfo_QryReq proto.InternalMessageInfo

func (m *QryReq) GetActId() int32 {
	if m != nil {
		return m.ActId
	}
	return 0
}

type QryResp struct {
	BasicInfo            *BasicInfo   `protobuf:"bytes,1,opt,name=basicInfo,proto3" json:"basicInfo,omitempty"`
	TaxiInfo             *TaxiInfo    `protobuf:"bytes,2,opt,name=taxiInfo,proto3" json:"taxiInfo,omitempty"`
	TakeoutInfo          *TakeoutInfo `protobuf:"bytes,3,opt,name=takeoutInfo,proto3" json:"takeoutInfo,omitempty"`
	OrderInfo            *OrderInfo   `protobuf:"bytes,4,opt,name=orderInfo,proto3" json:"orderInfo,omitempty"`
	OtherInfo            *OtherInfo   `protobuf:"bytes,5,opt,name=otherInfo,proto3" json:"otherInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QryResp) Reset()         { *m = QryResp{} }
func (m *QryResp) String() string { return proto.CompactTextString(m) }
func (*QryResp) ProtoMessage()    {}
func (*QryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{8}
}

func (m *QryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QryResp.Unmarshal(m, b)
}
func (m *QryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QryResp.Marshal(b, m, deterministic)
}
func (m *QryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QryResp.Merge(m, src)
}
func (m *QryResp) XXX_Size() int {
	return xxx_messageInfo_QryResp.Size(m)
}
func (m *QryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QryResp.DiscardUnknown(m)
}

var xxx_messageInfo_QryResp proto.InternalMessageInfo

func (m *QryResp) GetBasicInfo() *BasicInfo {
	if m != nil {
		return m.BasicInfo
	}
	return nil
}

func (m *QryResp) GetTaxiInfo() *TaxiInfo {
	if m != nil {
		return m.TaxiInfo
	}
	return nil
}

func (m *QryResp) GetTakeoutInfo() *TakeoutInfo {
	if m != nil {
		return m.TakeoutInfo
	}
	return nil
}

func (m *QryResp) GetOrderInfo() *OrderInfo {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

func (m *QryResp) GetOtherInfo() *OtherInfo {
	if m != nil {
		return m.OtherInfo
	}
	return nil
}

type TaxiInfo struct {
	DepartTime           string   `protobuf:"bytes,1,opt,name=departTime,proto3" json:"departTime,omitempty"`
	Origin               string   `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaxiInfo) Reset()         { *m = TaxiInfo{} }
func (m *TaxiInfo) String() string { return proto.CompactTextString(m) }
func (*TaxiInfo) ProtoMessage()    {}
func (*TaxiInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{9}
}

func (m *TaxiInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaxiInfo.Unmarshal(m, b)
}
func (m *TaxiInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaxiInfo.Marshal(b, m, deterministic)
}
func (m *TaxiInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaxiInfo.Merge(m, src)
}
func (m *TaxiInfo) XXX_Size() int {
	return xxx_messageInfo_TaxiInfo.Size(m)
}
func (m *TaxiInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TaxiInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TaxiInfo proto.InternalMessageInfo

func (m *TaxiInfo) GetDepartTime() string {
	if m != nil {
		return m.DepartTime
	}
	return ""
}

func (m *TaxiInfo) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *TaxiInfo) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type TakeoutInfo struct {
	Store                string   `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	OrderTime            string   `protobuf:"bytes,2,opt,name=orderTime,proto3" json:"orderTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TakeoutInfo) Reset()         { *m = TakeoutInfo{} }
func (m *TakeoutInfo) String() string { return proto.CompactTextString(m) }
func (*TakeoutInfo) ProtoMessage()    {}
func (*TakeoutInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{10}
}

func (m *TakeoutInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TakeoutInfo.Unmarshal(m, b)
}
func (m *TakeoutInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TakeoutInfo.Marshal(b, m, deterministic)
}
func (m *TakeoutInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TakeoutInfo.Merge(m, src)
}
func (m *TakeoutInfo) XXX_Size() int {
	return xxx_messageInfo_TakeoutInfo.Size(m)
}
func (m *TakeoutInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TakeoutInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TakeoutInfo proto.InternalMessageInfo

func (m *TakeoutInfo) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

func (m *TakeoutInfo) GetOrderTime() string {
	if m != nil {
		return m.OrderTime
	}
	return ""
}

type OrderInfo struct {
	Store                string   `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderInfo) Reset()         { *m = OrderInfo{} }
func (m *OrderInfo) String() string { return proto.CompactTextString(m) }
func (*OrderInfo) ProtoMessage()    {}
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{11}
}

func (m *OrderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfo.Unmarshal(m, b)
}
func (m *OrderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfo.Marshal(b, m, deterministic)
}
func (m *OrderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfo.Merge(m, src)
}
func (m *OrderInfo) XXX_Size() int {
	return xxx_messageInfo_OrderInfo.Size(m)
}
func (m *OrderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfo proto.InternalMessageInfo

func (m *OrderInfo) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

type OtherInfo struct {
	ActivityTime         string   `protobuf:"bytes,1,opt,name=activityTime,proto3" json:"activityTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OtherInfo) Reset()         { *m = OtherInfo{} }
func (m *OtherInfo) String() string { return proto.CompactTextString(m) }
func (*OtherInfo) ProtoMessage()    {}
func (*OtherInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{12}
}

func (m *OtherInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OtherInfo.Unmarshal(m, b)
}
func (m *OtherInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OtherInfo.Marshal(b, m, deterministic)
}
func (m *OtherInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OtherInfo.Merge(m, src)
}
func (m *OtherInfo) XXX_Size() int {
	return xxx_messageInfo_OtherInfo.Size(m)
}
func (m *OtherInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OtherInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OtherInfo proto.InternalMessageInfo

func (m *OtherInfo) GetActivityTime() string {
	if m != nil {
		return m.ActivityTime
	}
	return ""
}

func init() {
	proto.RegisterType((*BasicInfo)(nil), "activity.BasicInfo")
	proto.RegisterType((*PubReq)(nil), "activity.PubReq")
	proto.RegisterType((*PubResp)(nil), "activity.PubResp")
	proto.RegisterType((*MdfReq)(nil), "activity.MdfReq")
	proto.RegisterType((*MdfResp)(nil), "activity.MdfResp")
	proto.RegisterType((*DltReq)(nil), "activity.DltReq")
	proto.RegisterType((*DltResp)(nil), "activity.DltResp")
	proto.RegisterType((*QryReq)(nil), "activity.QryReq")
	proto.RegisterType((*QryResp)(nil), "activity.QryResp")
	proto.RegisterType((*TaxiInfo)(nil), "activity.TaxiInfo")
	proto.RegisterType((*TakeoutInfo)(nil), "activity.TakeoutInfo")
	proto.RegisterType((*OrderInfo)(nil), "activity.OrderInfo")
	proto.RegisterType((*OtherInfo)(nil), "activity.OtherInfo")
}

func init() { proto.RegisterFile("proto/activity.proto", fileDescriptor_970235c7b4e4341e) }

var fileDescriptor_970235c7b4e4341e = []byte{
	// 586 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x31, 0x73, 0xd3, 0x4c,
	0x10, 0xb5, 0x24, 0x4b, 0xb2, 0x56, 0x5f, 0x91, 0xef, 0x30, 0x8c, 0x86, 0x61, 0x32, 0xe6, 0x1a,
	0x5c, 0xd9, 0x60, 0x0a, 0xea, 0x40, 0x9a, 0x14, 0x19, 0x88, 0x48, 0x43, 0x29, 0x5b, 0xe7, 0xe4,
	0x06, 0x63, 0x89, 0xd3, 0x3a, 0x83, 0x3b, 0x7a, 0x7e, 0x06, 0xbf, 0x88, 0x9a, 0x3f, 0xc3, 0x68,
	0xa5, 0x93, 0xce, 0x0a, 0x66, 0xe2, 0xa4, 0xd3, 0xbe, 0x7d, 0xcf, 0x77, 0xbb, 0x6f, 0xf7, 0x0c,
	0xc3, 0x5c, 0x65, 0x98, 0x4d, 0x93, 0x05, 0xca, 0x1b, 0x89, 0xdb, 0x09, 0x85, 0x6c, 0xa0, 0x63,
	0xfe, 0xd3, 0x82, 0xe0, 0x6d, 0x52, 0xc8, 0xc5, 0xd9, 0x7a, 0x99, 0x31, 0x06, 0x7d, 0xdc, 0xe6,
	0x22, 0xb2, 0x47, 0xd6, 0x38, 0x88, 0xe9, 0x9b, 0x1d, 0x03, 0x2c, 0x94, 0x48, 0x50, 0x5c, 0xca,
	0x2f, 0x22, 0x72, 0x28, 0x63, 0x20, 0x2c, 0x02, 0x5f, 0xac, 0x53, 0x4a, 0xf6, 0x29, 0xa9, 0x43,
	0x36, 0x04, 0x17, 0x25, 0xae, 0x44, 0xe4, 0x12, 0x5e, 0x05, 0x6c, 0x04, 0x61, 0x2a, 0x8a, 0x85,
	0x92, 0x39, 0xca, 0x6c, 0x1d, 0x79, 0x94, 0x33, 0x21, 0x76, 0x04, 0x0e, 0x26, 0x57, 0x91, 0x3f,
	0x72, 0xc6, 0x41, 0x5c, 0x7e, 0xf2, 0xef, 0x36, 0x78, 0x1f, 0x36, 0xf3, 0x58, 0x7c, 0x65, 0x2f,
	0xa0, 0x2f, 0xd7, 0xcb, 0x8c, 0x2e, 0x12, 0xce, 0x1e, 0x4d, 0x9a, 0xca, 0x9a, 0x2a, 0x62, 0x22,
	0xb0, 0x09, 0x0c, 0x30, 0xf9, 0x26, 0x4b, 0x84, 0x2e, 0x16, 0xce, 0x58, 0x4b, 0xbe, 0xac, 0x33,
	0x71, 0xc3, 0x61, 0x6f, 0x20, 0xc4, 0xe4, 0xb3, 0xc8, 0x36, 0x48, 0x12, 0x97, 0x24, 0x8f, 0x4d,
	0x49, 0x93, 0x8c, 0x4d, 0x26, 0x7b, 0x05, 0x41, 0xa6, 0x52, 0xa1, 0x48, 0xe6, 0x75, 0xaf, 0xf5,
	0x5e, 0xa7, 0xe2, 0x96, 0x45, 0x12, 0xbc, 0xae, 0x25, 0xfe, 0x2d, 0x89, 0x4e, 0xc5, 0x2d, 0x8b,
	0x7f, 0x02, 0x9f, 0x3a, 0x50, 0xe4, 0xec, 0x09, 0x78, 0x05, 0x26, 0xb8, 0x29, 0x22, 0x6b, 0x64,
	0x8d, 0xdd, 0xb8, 0x8e, 0xba, 0x9d, 0xb5, 0x6f, 0x77, 0x76, 0x08, 0x6e, 0xb2, 0xc0, 0xb3, 0x94,
	0xba, 0xe7, 0xc6, 0x55, 0xc0, 0x7f, 0xdb, 0xe0, 0x9d, 0xa7, 0xcb, 0xb2, 0xbb, 0x0d, 0xc1, 0x32,
	0x08, 0x9d, 0x11, 0xb0, 0xff, 0x35, 0x02, 0xce, 0xee, 0x08, 0x74, 0xae, 0xd4, 0xdf, 0x6b, 0xb6,
	0xdb, 0x98, 0xbd, 0x63, 0x9c, 0x77, 0xb8, 0x71, 0xfe, 0xfd, 0x8c, 0x1b, 0x1c, 0x6e, 0x5c, 0x70,
	0x27, 0xe3, 0xde, 0x81, 0x4f, 0xcd, 0x7d, 0x88, 0x71, 0xfc, 0x18, 0xbc, 0xd3, 0x15, 0xee, 0x75,
	0xa8, 0x3c, 0x84, 0xf2, 0x0f, 0x3d, 0xe4, 0x42, 0x6d, 0xf7, 0x1f, 0xf2, 0xc3, 0x06, 0x9f, 0x08,
	0x45, 0x5e, 0x36, 0x62, 0xae, 0x17, 0x8e, 0x58, 0x7b, 0x76, 0xb1, 0x65, 0xed, 0xf8, 0x6a, 0x1f,
	0xee, 0xab, 0x73, 0x3f, 0x5f, 0xfb, 0x87, 0xfb, 0xea, 0xde, 0xc9, 0xd7, 0x14, 0x06, 0xfa, 0xd2,
	0xe5, 0x82, 0xa4, 0x22, 0x4f, 0x14, 0xd2, 0x0e, 0x58, 0xd5, 0x82, 0xb4, 0x48, 0xe9, 0x49, 0xa6,
	0xe4, 0x95, 0xd4, 0x6d, 0xaf, 0xa3, 0xda, 0x13, 0x94, 0xeb, 0x84, 0x3c, 0x71, 0x1a, 0x4f, 0x34,
	0xc4, 0x4f, 0x20, 0x34, 0xea, 0x2c, 0x8d, 0x29, 0x30, 0x53, 0xfa, 0x8c, 0x2a, 0x60, 0xcf, 0xea,
	0x82, 0x8d, 0xf5, 0x6c, 0x01, 0xfe, 0x1c, 0x82, 0xa6, 0xe6, 0xbf, 0xff, 0x00, 0x9f, 0x42, 0xd0,
	0xd4, 0xc8, 0x38, 0xfc, 0xa7, 0x2b, 0x37, 0xca, 0xd9, 0xc1, 0x66, 0xbf, 0x2c, 0x08, 0x4f, 0x6a,
	0xe0, 0xa3, 0xba, 0x61, 0x2f, 0xe9, 0x75, 0x5a, 0xc9, 0xe2, 0x9a, 0x1d, 0xb5, 0x7d, 0xab, 0x9e,
	0xec, 0xa7, 0xff, 0x77, 0x90, 0x22, 0xe7, 0x3d, 0x36, 0x05, 0xef, 0x3c, 0x4b, 0xe5, 0x72, 0x6b,
	0x0a, 0xaa, 0x57, 0xc8, 0x14, 0xd4, 0xab, 0x53, 0x09, 0x4e, 0xc5, 0x4a, 0xa0, 0x30, 0x05, 0xd5,
	0x52, 0x98, 0x82, 0x7a, 0x0d, 0x78, 0x8f, 0x4d, 0xc0, 0xbd, 0xd8, 0x08, 0xb5, 0x73, 0x40, 0x35,
	0xdf, 0x26, 0xbf, 0x1e, 0x68, 0xde, 0x9b, 0x7b, 0xf4, 0xdf, 0xf8, 0xfa, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x71, 0xad, 0xb2, 0xc9, 0x33, 0x07, 0x00, 0x00,
}
