// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/activity.proto

package activity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ActivitySrv service

type ActivitySrvService interface {
	Publish(ctx context.Context, in *PubReq, opts ...client.CallOption) (*PubResp, error)
	Modify(ctx context.Context, in *MdfReq, opts ...client.CallOption) (*MdfResp, error)
	Delete(ctx context.Context, in *DltReq, opts ...client.CallOption) (*DltResp, error)
	Query(ctx context.Context, in *QryReq, opts ...client.CallOption) (*QryResp, error)
	Comment(ctx context.Context, in *CmtReq, opts ...client.CallOption) (*CmtResp, error)
	GenTags(ctx context.Context, in *TagReq, opts ...client.CallOption) (*TagResp, error)
	AddTags(ctx context.Context, in *AddTagsReq, opts ...client.CallOption) (*AddTagsResp, error)
	Recommendation(ctx context.Context, in *RecommendReq, opts ...client.CallOption) (*RecommendResp, error)
}

type activitySrvService struct {
	c    client.Client
	name string
}

func NewActivitySrvService(name string, c client.Client) ActivitySrvService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "activity"
	}
	return &activitySrvService{
		c:    c,
		name: name,
	}
}

func (c *activitySrvService) Publish(ctx context.Context, in *PubReq, opts ...client.CallOption) (*PubResp, error) {
	req := c.c.NewRequest(c.name, "ActivitySrv.Publish", in)
	out := new(PubResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitySrvService) Modify(ctx context.Context, in *MdfReq, opts ...client.CallOption) (*MdfResp, error) {
	req := c.c.NewRequest(c.name, "ActivitySrv.Modify", in)
	out := new(MdfResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitySrvService) Delete(ctx context.Context, in *DltReq, opts ...client.CallOption) (*DltResp, error) {
	req := c.c.NewRequest(c.name, "ActivitySrv.Delete", in)
	out := new(DltResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitySrvService) Query(ctx context.Context, in *QryReq, opts ...client.CallOption) (*QryResp, error) {
	req := c.c.NewRequest(c.name, "ActivitySrv.Query", in)
	out := new(QryResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitySrvService) Comment(ctx context.Context, in *CmtReq, opts ...client.CallOption) (*CmtResp, error) {
	req := c.c.NewRequest(c.name, "ActivitySrv.Comment", in)
	out := new(CmtResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitySrvService) GenTags(ctx context.Context, in *TagReq, opts ...client.CallOption) (*TagResp, error) {
	req := c.c.NewRequest(c.name, "ActivitySrv.GenTags", in)
	out := new(TagResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitySrvService) AddTags(ctx context.Context, in *AddTagsReq, opts ...client.CallOption) (*AddTagsResp, error) {
	req := c.c.NewRequest(c.name, "ActivitySrv.AddTags", in)
	out := new(AddTagsResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activitySrvService) Recommendation(ctx context.Context, in *RecommendReq, opts ...client.CallOption) (*RecommendResp, error) {
	req := c.c.NewRequest(c.name, "ActivitySrv.Recommendation", in)
	out := new(RecommendResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ActivitySrv service

type ActivitySrvHandler interface {
	Publish(context.Context, *PubReq, *PubResp) error
	Modify(context.Context, *MdfReq, *MdfResp) error
	Delete(context.Context, *DltReq, *DltResp) error
	Query(context.Context, *QryReq, *QryResp) error
	Comment(context.Context, *CmtReq, *CmtResp) error
	GenTags(context.Context, *TagReq, *TagResp) error
	AddTags(context.Context, *AddTagsReq, *AddTagsResp) error
	Recommendation(context.Context, *RecommendReq, *RecommendResp) error
}

func RegisterActivitySrvHandler(s server.Server, hdlr ActivitySrvHandler, opts ...server.HandlerOption) error {
	type activitySrv interface {
		Publish(ctx context.Context, in *PubReq, out *PubResp) error
		Modify(ctx context.Context, in *MdfReq, out *MdfResp) error
		Delete(ctx context.Context, in *DltReq, out *DltResp) error
		Query(ctx context.Context, in *QryReq, out *QryResp) error
		Comment(ctx context.Context, in *CmtReq, out *CmtResp) error
		GenTags(ctx context.Context, in *TagReq, out *TagResp) error
		AddTags(ctx context.Context, in *AddTagsReq, out *AddTagsResp) error
		Recommendation(ctx context.Context, in *RecommendReq, out *RecommendResp) error
	}
	type ActivitySrv struct {
		activitySrv
	}
	h := &activitySrvHandler{hdlr}
	return s.Handle(s.NewHandler(&ActivitySrv{h}, opts...))
}

type activitySrvHandler struct {
	ActivitySrvHandler
}

func (h *activitySrvHandler) Publish(ctx context.Context, in *PubReq, out *PubResp) error {
	return h.ActivitySrvHandler.Publish(ctx, in, out)
}

func (h *activitySrvHandler) Modify(ctx context.Context, in *MdfReq, out *MdfResp) error {
	return h.ActivitySrvHandler.Modify(ctx, in, out)
}

func (h *activitySrvHandler) Delete(ctx context.Context, in *DltReq, out *DltResp) error {
	return h.ActivitySrvHandler.Delete(ctx, in, out)
}

func (h *activitySrvHandler) Query(ctx context.Context, in *QryReq, out *QryResp) error {
	return h.ActivitySrvHandler.Query(ctx, in, out)
}

func (h *activitySrvHandler) Comment(ctx context.Context, in *CmtReq, out *CmtResp) error {
	return h.ActivitySrvHandler.Comment(ctx, in, out)
}

func (h *activitySrvHandler) GenTags(ctx context.Context, in *TagReq, out *TagResp) error {
	return h.ActivitySrvHandler.GenTags(ctx, in, out)
}

func (h *activitySrvHandler) AddTags(ctx context.Context, in *AddTagsReq, out *AddTagsResp) error {
	return h.ActivitySrvHandler.AddTags(ctx, in, out)
}

func (h *activitySrvHandler) Recommendation(ctx context.Context, in *RecommendReq, out *RecommendResp) error {
	return h.ActivitySrvHandler.Recommendation(ctx, in, out)
}
