// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/activity.proto

package activity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BasicInfo struct {
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	CreateTime           string   `protobuf:"bytes,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	EndTime              string   `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Tag                  []string `protobuf:"bytes,7,rep,name=tag,proto3" json:"tag,omitempty"`
	Images               []string `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`
	Status               int32    `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	MaxMember            int32    `protobuf:"varint,10,opt,name=maxMember,proto3" json:"maxMember,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BasicInfo) Reset()         { *m = BasicInfo{} }
func (m *BasicInfo) String() string { return proto.CompactTextString(m) }
func (*BasicInfo) ProtoMessage()    {}
func (*BasicInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{0}
}

func (m *BasicInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BasicInfo.Unmarshal(m, b)
}
func (m *BasicInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BasicInfo.Marshal(b, m, deterministic)
}
func (m *BasicInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicInfo.Merge(m, src)
}
func (m *BasicInfo) XXX_Size() int {
	return xxx_messageInfo_BasicInfo.Size(m)
}
func (m *BasicInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BasicInfo proto.InternalMessageInfo

func (m *BasicInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *BasicInfo) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *BasicInfo) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *BasicInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BasicInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BasicInfo) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *BasicInfo) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *BasicInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BasicInfo) GetMaxMember() int32 {
	if m != nil {
		return m.MaxMember
	}
	return 0
}

type PubReq struct {
	Info                 *BasicInfo   `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	TaxiInfo             *TaxiInfo    `protobuf:"bytes,4,opt,name=taxiInfo,proto3" json:"taxiInfo,omitempty"`
	TakeoutInfo          *TakeoutInfo `protobuf:"bytes,5,opt,name=takeoutInfo,proto3" json:"takeoutInfo,omitempty"`
	OrderInfo            *OrderInfo   `protobuf:"bytes,6,opt,name=orderInfo,proto3" json:"orderInfo,omitempty"`
	OtherInfo            *OtherInfo   `protobuf:"bytes,7,opt,name=otherInfo,proto3" json:"otherInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PubReq) Reset()         { *m = PubReq{} }
func (m *PubReq) String() string { return proto.CompactTextString(m) }
func (*PubReq) ProtoMessage()    {}
func (*PubReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{1}
}

func (m *PubReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubReq.Unmarshal(m, b)
}
func (m *PubReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubReq.Marshal(b, m, deterministic)
}
func (m *PubReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubReq.Merge(m, src)
}
func (m *PubReq) XXX_Size() int {
	return xxx_messageInfo_PubReq.Size(m)
}
func (m *PubReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PubReq.DiscardUnknown(m)
}

var xxx_messageInfo_PubReq proto.InternalMessageInfo

func (m *PubReq) GetInfo() *BasicInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *PubReq) GetTaxiInfo() *TaxiInfo {
	if m != nil {
		return m.TaxiInfo
	}
	return nil
}

func (m *PubReq) GetTakeoutInfo() *TakeoutInfo {
	if m != nil {
		return m.TakeoutInfo
	}
	return nil
}

func (m *PubReq) GetOrderInfo() *OrderInfo {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

func (m *PubReq) GetOtherInfo() *OtherInfo {
	if m != nil {
		return m.OtherInfo
	}
	return nil
}

type PubResp struct {
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ActId                int32    `protobuf:"varint,3,opt,name=actId,proto3" json:"actId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubResp) Reset()         { *m = PubResp{} }
func (m *PubResp) String() string { return proto.CompactTextString(m) }
func (*PubResp) ProtoMessage()    {}
func (*PubResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{2}
}

func (m *PubResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubResp.Unmarshal(m, b)
}
func (m *PubResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubResp.Marshal(b, m, deterministic)
}
func (m *PubResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubResp.Merge(m, src)
}
func (m *PubResp) XXX_Size() int {
	return xxx_messageInfo_PubResp.Size(m)
}
func (m *PubResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PubResp.DiscardUnknown(m)
}

var xxx_messageInfo_PubResp proto.InternalMessageInfo

func (m *PubResp) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PubResp) GetActId() int32 {
	if m != nil {
		return m.ActId
	}
	return 0
}

type MdfReq struct {
	ActId                int32        `protobuf:"varint,1,opt,name=actId,proto3" json:"actId,omitempty"`
	CreateTime           string       `protobuf:"bytes,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	EndTime              string       `protobuf:"bytes,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Description          string       `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MaxMember            int32        `protobuf:"varint,11,opt,name=maxMember,proto3" json:"maxMember,omitempty"`
	Tag                  []string     `protobuf:"bytes,5,rep,name=tag,proto3" json:"tag,omitempty"`
	Images               []string     `protobuf:"bytes,10,rep,name=images,proto3" json:"images,omitempty"`
	TaxiInfo             *TaxiInfo    `protobuf:"bytes,6,opt,name=taxiInfo,proto3" json:"taxiInfo,omitempty"`
	TakeoutInfo          *TakeoutInfo `protobuf:"bytes,7,opt,name=takeoutInfo,proto3" json:"takeoutInfo,omitempty"`
	OrderInfo            *OrderInfo   `protobuf:"bytes,8,opt,name=orderInfo,proto3" json:"orderInfo,omitempty"`
	OtherInfo            *OtherInfo   `protobuf:"bytes,9,opt,name=otherInfo,proto3" json:"otherInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MdfReq) Reset()         { *m = MdfReq{} }
func (m *MdfReq) String() string { return proto.CompactTextString(m) }
func (*MdfReq) ProtoMessage()    {}
func (*MdfReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{3}
}

func (m *MdfReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MdfReq.Unmarshal(m, b)
}
func (m *MdfReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MdfReq.Marshal(b, m, deterministic)
}
func (m *MdfReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MdfReq.Merge(m, src)
}
func (m *MdfReq) XXX_Size() int {
	return xxx_messageInfo_MdfReq.Size(m)
}
func (m *MdfReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MdfReq.DiscardUnknown(m)
}

var xxx_messageInfo_MdfReq proto.InternalMessageInfo

func (m *MdfReq) GetActId() int32 {
	if m != nil {
		return m.ActId
	}
	return 0
}

func (m *MdfReq) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *MdfReq) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *MdfReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MdfReq) GetMaxMember() int32 {
	if m != nil {
		return m.MaxMember
	}
	return 0
}

func (m *MdfReq) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

func (m *MdfReq) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *MdfReq) GetTaxiInfo() *TaxiInfo {
	if m != nil {
		return m.TaxiInfo
	}
	return nil
}

func (m *MdfReq) GetTakeoutInfo() *TakeoutInfo {
	if m != nil {
		return m.TakeoutInfo
	}
	return nil
}

func (m *MdfReq) GetOrderInfo() *OrderInfo {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

func (m *MdfReq) GetOtherInfo() *OtherInfo {
	if m != nil {
		return m.OtherInfo
	}
	return nil
}

type MdfResp struct {
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MdfResp) Reset()         { *m = MdfResp{} }
func (m *MdfResp) String() string { return proto.CompactTextString(m) }
func (*MdfResp) ProtoMessage()    {}
func (*MdfResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{4}
}

func (m *MdfResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MdfResp.Unmarshal(m, b)
}
func (m *MdfResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MdfResp.Marshal(b, m, deterministic)
}
func (m *MdfResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MdfResp.Merge(m, src)
}
func (m *MdfResp) XXX_Size() int {
	return xxx_messageInfo_MdfResp.Size(m)
}
func (m *MdfResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MdfResp.DiscardUnknown(m)
}

var xxx_messageInfo_MdfResp proto.InternalMessageInfo

func (m *MdfResp) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type DltReq struct {
	ActId                int32    `protobuf:"varint,1,opt,name=actId,proto3" json:"actId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DltReq) Reset()         { *m = DltReq{} }
func (m *DltReq) String() string { return proto.CompactTextString(m) }
func (*DltReq) ProtoMessage()    {}
func (*DltReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{5}
}

func (m *DltReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DltReq.Unmarshal(m, b)
}
func (m *DltReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DltReq.Marshal(b, m, deterministic)
}
func (m *DltReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DltReq.Merge(m, src)
}
func (m *DltReq) XXX_Size() int {
	return xxx_messageInfo_DltReq.Size(m)
}
func (m *DltReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DltReq.DiscardUnknown(m)
}

var xxx_messageInfo_DltReq proto.InternalMessageInfo

func (m *DltReq) GetActId() int32 {
	if m != nil {
		return m.ActId
	}
	return 0
}

type DltResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DltResp) Reset()         { *m = DltResp{} }
func (m *DltResp) String() string { return proto.CompactTextString(m) }
func (*DltResp) ProtoMessage()    {}
func (*DltResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{6}
}

func (m *DltResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DltResp.Unmarshal(m, b)
}
func (m *DltResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DltResp.Marshal(b, m, deterministic)
}
func (m *DltResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DltResp.Merge(m, src)
}
func (m *DltResp) XXX_Size() int {
	return xxx_messageInfo_DltResp.Size(m)
}
func (m *DltResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DltResp.DiscardUnknown(m)
}

var xxx_messageInfo_DltResp proto.InternalMessageInfo

func (m *DltResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DltResp) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type QryReq struct {
	ActId                int32    `protobuf:"varint,1,opt,name=actId,proto3" json:"actId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QryReq) Reset()         { *m = QryReq{} }
func (m *QryReq) String() string { return proto.CompactTextString(m) }
func (*QryReq) ProtoMessage()    {}
func (*QryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{7}
}

func (m *QryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QryReq.Unmarshal(m, b)
}
func (m *QryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QryReq.Marshal(b, m, deterministic)
}
func (m *QryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QryReq.Merge(m, src)
}
func (m *QryReq) XXX_Size() int {
	return xxx_messageInfo_QryReq.Size(m)
}
func (m *QryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QryReq.DiscardUnknown(m)
}

var xxx_messageInfo_QryReq proto.InternalMessageInfo

func (m *QryReq) GetActId() int32 {
	if m != nil {
		return m.ActId
	}
	return 0
}

type QryResp struct {
	BasicInfo            *BasicInfo   `protobuf:"bytes,1,opt,name=basicInfo,proto3" json:"basicInfo,omitempty"`
	TaxiInfo             *TaxiInfo    `protobuf:"bytes,2,opt,name=taxiInfo,proto3" json:"taxiInfo,omitempty"`
	TakeoutInfo          *TakeoutInfo `protobuf:"bytes,3,opt,name=takeoutInfo,proto3" json:"takeoutInfo,omitempty"`
	OrderInfo            *OrderInfo   `protobuf:"bytes,4,opt,name=orderInfo,proto3" json:"orderInfo,omitempty"`
	OtherInfo            *OtherInfo   `protobuf:"bytes,5,opt,name=otherInfo,proto3" json:"otherInfo,omitempty"`
	Comments             []*Comment   `protobuf:"bytes,7,rep,name=comments,proto3" json:"comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *QryResp) Reset()         { *m = QryResp{} }
func (m *QryResp) String() string { return proto.CompactTextString(m) }
func (*QryResp) ProtoMessage()    {}
func (*QryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{8}
}

func (m *QryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QryResp.Unmarshal(m, b)
}
func (m *QryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QryResp.Marshal(b, m, deterministic)
}
func (m *QryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QryResp.Merge(m, src)
}
func (m *QryResp) XXX_Size() int {
	return xxx_messageInfo_QryResp.Size(m)
}
func (m *QryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QryResp.DiscardUnknown(m)
}

var xxx_messageInfo_QryResp proto.InternalMessageInfo

func (m *QryResp) GetBasicInfo() *BasicInfo {
	if m != nil {
		return m.BasicInfo
	}
	return nil
}

func (m *QryResp) GetTaxiInfo() *TaxiInfo {
	if m != nil {
		return m.TaxiInfo
	}
	return nil
}

func (m *QryResp) GetTakeoutInfo() *TakeoutInfo {
	if m != nil {
		return m.TakeoutInfo
	}
	return nil
}

func (m *QryResp) GetOrderInfo() *OrderInfo {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

func (m *QryResp) GetOtherInfo() *OtherInfo {
	if m != nil {
		return m.OtherInfo
	}
	return nil
}

func (m *QryResp) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

type TaxiInfo struct {
	DepartTime           string   `protobuf:"bytes,1,opt,name=departTime,proto3" json:"departTime,omitempty"`
	Origin               []byte   `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination          []byte   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaxiInfo) Reset()         { *m = TaxiInfo{} }
func (m *TaxiInfo) String() string { return proto.CompactTextString(m) }
func (*TaxiInfo) ProtoMessage()    {}
func (*TaxiInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{9}
}

func (m *TaxiInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaxiInfo.Unmarshal(m, b)
}
func (m *TaxiInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaxiInfo.Marshal(b, m, deterministic)
}
func (m *TaxiInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaxiInfo.Merge(m, src)
}
func (m *TaxiInfo) XXX_Size() int {
	return xxx_messageInfo_TaxiInfo.Size(m)
}
func (m *TaxiInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TaxiInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TaxiInfo proto.InternalMessageInfo

func (m *TaxiInfo) GetDepartTime() string {
	if m != nil {
		return m.DepartTime
	}
	return ""
}

func (m *TaxiInfo) GetOrigin() []byte {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *TaxiInfo) GetDestination() []byte {
	if m != nil {
		return m.Destination
	}
	return nil
}

type TakeoutInfo struct {
	Store                string   `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	OrderTime            string   `protobuf:"bytes,2,opt,name=orderTime,proto3" json:"orderTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TakeoutInfo) Reset()         { *m = TakeoutInfo{} }
func (m *TakeoutInfo) String() string { return proto.CompactTextString(m) }
func (*TakeoutInfo) ProtoMessage()    {}
func (*TakeoutInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{10}
}

func (m *TakeoutInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TakeoutInfo.Unmarshal(m, b)
}
func (m *TakeoutInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TakeoutInfo.Marshal(b, m, deterministic)
}
func (m *TakeoutInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TakeoutInfo.Merge(m, src)
}
func (m *TakeoutInfo) XXX_Size() int {
	return xxx_messageInfo_TakeoutInfo.Size(m)
}
func (m *TakeoutInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TakeoutInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TakeoutInfo proto.InternalMessageInfo

func (m *TakeoutInfo) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

func (m *TakeoutInfo) GetOrderTime() string {
	if m != nil {
		return m.OrderTime
	}
	return ""
}

type OrderInfo struct {
	Store                string   `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderInfo) Reset()         { *m = OrderInfo{} }
func (m *OrderInfo) String() string { return proto.CompactTextString(m) }
func (*OrderInfo) ProtoMessage()    {}
func (*OrderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{11}
}

func (m *OrderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfo.Unmarshal(m, b)
}
func (m *OrderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfo.Marshal(b, m, deterministic)
}
func (m *OrderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfo.Merge(m, src)
}
func (m *OrderInfo) XXX_Size() int {
	return xxx_messageInfo_OrderInfo.Size(m)
}
func (m *OrderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfo proto.InternalMessageInfo

func (m *OrderInfo) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

type OtherInfo struct {
	ActivityTime         string   `protobuf:"bytes,1,opt,name=activityTime,proto3" json:"activityTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OtherInfo) Reset()         { *m = OtherInfo{} }
func (m *OtherInfo) String() string { return proto.CompactTextString(m) }
func (*OtherInfo) ProtoMessage()    {}
func (*OtherInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{12}
}

func (m *OtherInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OtherInfo.Unmarshal(m, b)
}
func (m *OtherInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OtherInfo.Marshal(b, m, deterministic)
}
func (m *OtherInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OtherInfo.Merge(m, src)
}
func (m *OtherInfo) XXX_Size() int {
	return xxx_messageInfo_OtherInfo.Size(m)
}
func (m *OtherInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OtherInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OtherInfo proto.InternalMessageInfo

func (m *OtherInfo) GetActivityTime() string {
	if m != nil {
		return m.ActivityTime
	}
	return ""
}

type CmtReq struct {
	ActId                int32    `protobuf:"varint,1,opt,name=actId,proto3" json:"actId,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ReceiverId           int32    `protobuf:"varint,4,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Time                 string   `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmtReq) Reset()         { *m = CmtReq{} }
func (m *CmtReq) String() string { return proto.CompactTextString(m) }
func (*CmtReq) ProtoMessage()    {}
func (*CmtReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{13}
}

func (m *CmtReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmtReq.Unmarshal(m, b)
}
func (m *CmtReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmtReq.Marshal(b, m, deterministic)
}
func (m *CmtReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmtReq.Merge(m, src)
}
func (m *CmtReq) XXX_Size() int {
	return xxx_messageInfo_CmtReq.Size(m)
}
func (m *CmtReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CmtReq.DiscardUnknown(m)
}

var xxx_messageInfo_CmtReq proto.InternalMessageInfo

func (m *CmtReq) GetActId() int32 {
	if m != nil {
		return m.ActId
	}
	return 0
}

func (m *CmtReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CmtReq) GetReceiverId() int32 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *CmtReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CmtReq) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type CmtResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmtResp) Reset()         { *m = CmtResp{} }
func (m *CmtResp) String() string { return proto.CompactTextString(m) }
func (*CmtResp) ProtoMessage()    {}
func (*CmtResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{14}
}

func (m *CmtResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmtResp.Unmarshal(m, b)
}
func (m *CmtResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmtResp.Marshal(b, m, deterministic)
}
func (m *CmtResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmtResp.Merge(m, src)
}
func (m *CmtResp) XXX_Size() int {
	return xxx_messageInfo_CmtResp.Size(m)
}
func (m *CmtResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CmtResp.DiscardUnknown(m)
}

var xxx_messageInfo_CmtResp proto.InternalMessageInfo

func (m *CmtResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CmtResp) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Comment struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ReceiverId           int32    `protobuf:"varint,2,opt,name=receiverId,proto3" json:"receiverId,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Time                 string   `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{15}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Comment) GetReceiverId() int32 {
	if m != nil {
		return m.ReceiverId
	}
	return 0
}

func (m *Comment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Comment) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type TagReq struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagReq) Reset()         { *m = TagReq{} }
func (m *TagReq) String() string { return proto.CompactTextString(m) }
func (*TagReq) ProtoMessage()    {}
func (*TagReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{16}
}

func (m *TagReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagReq.Unmarshal(m, b)
}
func (m *TagReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagReq.Marshal(b, m, deterministic)
}
func (m *TagReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagReq.Merge(m, src)
}
func (m *TagReq) XXX_Size() int {
	return xxx_messageInfo_TagReq.Size(m)
}
func (m *TagReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TagReq.DiscardUnknown(m)
}

var xxx_messageInfo_TagReq proto.InternalMessageInfo

func (m *TagReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TagReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type TagResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Tag                  []string `protobuf:"bytes,2,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagResp) Reset()         { *m = TagResp{} }
func (m *TagResp) String() string { return proto.CompactTextString(m) }
func (*TagResp) ProtoMessage()    {}
func (*TagResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{17}
}

func (m *TagResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagResp.Unmarshal(m, b)
}
func (m *TagResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagResp.Marshal(b, m, deterministic)
}
func (m *TagResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagResp.Merge(m, src)
}
func (m *TagResp) XXX_Size() int {
	return xxx_messageInfo_TagResp.Size(m)
}
func (m *TagResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TagResp.DiscardUnknown(m)
}

var xxx_messageInfo_TagResp proto.InternalMessageInfo

func (m *TagResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *TagResp) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

type AddTagsReq struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTagsReq) Reset()         { *m = AddTagsReq{} }
func (m *AddTagsReq) String() string { return proto.CompactTextString(m) }
func (*AddTagsReq) ProtoMessage()    {}
func (*AddTagsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{18}
}

func (m *AddTagsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTagsReq.Unmarshal(m, b)
}
func (m *AddTagsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTagsReq.Marshal(b, m, deterministic)
}
func (m *AddTagsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTagsReq.Merge(m, src)
}
func (m *AddTagsReq) XXX_Size() int {
	return xxx_messageInfo_AddTagsReq.Size(m)
}
func (m *AddTagsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTagsReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddTagsReq proto.InternalMessageInfo

func (m *AddTagsReq) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *AddTagsReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type AddTagsResp struct {
	Num                  int32    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTagsResp) Reset()         { *m = AddTagsResp{} }
func (m *AddTagsResp) String() string { return proto.CompactTextString(m) }
func (*AddTagsResp) ProtoMessage()    {}
func (*AddTagsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{19}
}

func (m *AddTagsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTagsResp.Unmarshal(m, b)
}
func (m *AddTagsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTagsResp.Marshal(b, m, deterministic)
}
func (m *AddTagsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTagsResp.Merge(m, src)
}
func (m *AddTagsResp) XXX_Size() int {
	return xxx_messageInfo_AddTagsResp.Size(m)
}
func (m *AddTagsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTagsResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddTagsResp proto.InternalMessageInfo

func (m *AddTagsResp) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type RecommendReq struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecommendReq) Reset()         { *m = RecommendReq{} }
func (m *RecommendReq) String() string { return proto.CompactTextString(m) }
func (*RecommendReq) ProtoMessage()    {}
func (*RecommendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{20}
}

func (m *RecommendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecommendReq.Unmarshal(m, b)
}
func (m *RecommendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecommendReq.Marshal(b, m, deterministic)
}
func (m *RecommendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecommendReq.Merge(m, src)
}
func (m *RecommendReq) XXX_Size() int {
	return xxx_messageInfo_RecommendReq.Size(m)
}
func (m *RecommendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RecommendReq.DiscardUnknown(m)
}

var xxx_messageInfo_RecommendReq proto.InternalMessageInfo

func (m *RecommendReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type RecommendResp struct {
	//
	//0 for the user or all the another users have no behavior
	//1 for the nearest user has no activity
	//2 for OK.
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ActId                []int32  `protobuf:"varint,1,rep,packed,name=actId,proto3" json:"actId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecommendResp) Reset()         { *m = RecommendResp{} }
func (m *RecommendResp) String() string { return proto.CompactTextString(m) }
func (*RecommendResp) ProtoMessage()    {}
func (*RecommendResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{21}
}

func (m *RecommendResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecommendResp.Unmarshal(m, b)
}
func (m *RecommendResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecommendResp.Marshal(b, m, deterministic)
}
func (m *RecommendResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecommendResp.Merge(m, src)
}
func (m *RecommendResp) XXX_Size() int {
	return xxx_messageInfo_RecommendResp.Size(m)
}
func (m *RecommendResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RecommendResp.DiscardUnknown(m)
}

var xxx_messageInfo_RecommendResp proto.InternalMessageInfo

func (m *RecommendResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *RecommendResp) GetActId() []int32 {
	if m != nil {
		return m.ActId
	}
	return nil
}

func init() {
	proto.RegisterType((*BasicInfo)(nil), "activity.BasicInfo")
	proto.RegisterType((*PubReq)(nil), "activity.PubReq")
	proto.RegisterType((*PubResp)(nil), "activity.PubResp")
	proto.RegisterType((*MdfReq)(nil), "activity.MdfReq")
	proto.RegisterType((*MdfResp)(nil), "activity.MdfResp")
	proto.RegisterType((*DltReq)(nil), "activity.DltReq")
	proto.RegisterType((*DltResp)(nil), "activity.DltResp")
	proto.RegisterType((*QryReq)(nil), "activity.QryReq")
	proto.RegisterType((*QryResp)(nil), "activity.QryResp")
	proto.RegisterType((*TaxiInfo)(nil), "activity.TaxiInfo")
	proto.RegisterType((*TakeoutInfo)(nil), "activity.TakeoutInfo")
	proto.RegisterType((*OrderInfo)(nil), "activity.OrderInfo")
	proto.RegisterType((*OtherInfo)(nil), "activity.OtherInfo")
	proto.RegisterType((*CmtReq)(nil), "activity.CmtReq")
	proto.RegisterType((*CmtResp)(nil), "activity.CmtResp")
	proto.RegisterType((*Comment)(nil), "activity.Comment")
	proto.RegisterType((*TagReq)(nil), "activity.TagReq")
	proto.RegisterType((*TagResp)(nil), "activity.TagResp")
	proto.RegisterType((*AddTagsReq)(nil), "activity.AddTagsReq")
	proto.RegisterType((*AddTagsResp)(nil), "activity.AddTagsResp")
	proto.RegisterType((*RecommendReq)(nil), "activity.RecommendReq")
	proto.RegisterType((*RecommendResp)(nil), "activity.RecommendResp")
}

func init() { proto.RegisterFile("proto/activity.proto", fileDescriptor_970235c7b4e4341e) }

var fileDescriptor_970235c7b4e4341e = []byte{
	// 893 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcd, 0x6e, 0xe4, 0x44,
	0x10, 0x8e, 0xed, 0xb1, 0x3d, 0x2e, 0x07, 0xb4, 0xdb, 0x64, 0x17, 0x2b, 0x42, 0x4b, 0xe8, 0x03,
	0x44, 0x42, 0x24, 0x90, 0x3d, 0xb0, 0x17, 0x24, 0xc2, 0xac, 0x84, 0x72, 0x88, 0x60, 0x4d, 0x5e,
	0xa0, 0x33, 0xee, 0xcc, 0xb6, 0x88, 0x7f, 0x70, 0xf7, 0x44, 0xc9, 0x8d, 0x03, 0x2f, 0xc0, 0xbb,
	0x70, 0xe2, 0xad, 0x78, 0x03, 0xd4, 0xd5, 0x6d, 0xbb, 0x3d, 0x99, 0x89, 0x32, 0xd9, 0x9b, 0xeb,
	0xe7, 0xeb, 0xae, 0xaa, 0xaf, 0xaa, 0xda, 0xb0, 0xd7, 0xb4, 0xb5, 0xaa, 0x8f, 0xd9, 0x5c, 0x89,
	0x1b, 0xa1, 0xee, 0x8e, 0x50, 0x24, 0xd3, 0x4e, 0xa6, 0xff, 0x79, 0x90, 0xfc, 0xc4, 0xa4, 0x98,
	0x9f, 0x55, 0x57, 0x35, 0x21, 0x30, 0x51, 0x77, 0x0d, 0xcf, 0xfc, 0x03, 0xef, 0x30, 0xc9, 0xf1,
	0x9b, 0xbc, 0x02, 0x98, 0xb7, 0x9c, 0x29, 0x7e, 0x21, 0x4a, 0x9e, 0x05, 0x68, 0x71, 0x34, 0x24,
	0x83, 0x98, 0x57, 0x05, 0x1a, 0x27, 0x68, 0xec, 0x44, 0xb2, 0x07, 0xa1, 0x12, 0xea, 0x9a, 0x67,
	0x21, 0xea, 0x8d, 0x40, 0x0e, 0x20, 0x2d, 0xb8, 0x9c, 0xb7, 0xa2, 0x51, 0xa2, 0xae, 0xb2, 0x08,
	0x6d, 0xae, 0x8a, 0x3c, 0x83, 0x40, 0xb1, 0x45, 0x16, 0x1f, 0x04, 0x87, 0x49, 0xae, 0x3f, 0xc9,
	0x4b, 0x88, 0x44, 0xc9, 0x16, 0x5c, 0x66, 0x53, 0x54, 0x5a, 0x49, 0xeb, 0xa5, 0x62, 0x6a, 0x29,
	0xb3, 0xe4, 0xc0, 0x3b, 0x0c, 0x73, 0x2b, 0x91, 0xcf, 0x20, 0x29, 0xd9, 0xed, 0x39, 0x2f, 0x2f,
	0x79, 0x9b, 0x01, 0x9a, 0x06, 0x05, 0xfd, 0xd3, 0x87, 0xe8, 0xd7, 0xe5, 0x65, 0xce, 0xff, 0x20,
	0x5f, 0xc1, 0x44, 0x54, 0x57, 0x35, 0xa6, 0x95, 0x9e, 0x7c, 0x72, 0xd4, 0xd7, 0xa9, 0xaf, 0x49,
	0x8e, 0x0e, 0xe4, 0x08, 0xa6, 0x8a, 0xdd, 0x0a, 0xad, 0xc1, 0x34, 0xd3, 0x13, 0x32, 0x38, 0x5f,
	0x58, 0x4b, 0xde, 0xfb, 0x90, 0xef, 0x21, 0x55, 0xec, 0x77, 0x5e, 0x2f, 0x15, 0x42, 0x42, 0x84,
	0xbc, 0x70, 0x21, 0xbd, 0x31, 0x77, 0x3d, 0xc9, 0x77, 0x90, 0xd4, 0x6d, 0xc1, 0x5b, 0x84, 0x45,
	0xab, 0x61, 0xfd, 0xd2, 0x99, 0xf2, 0xc1, 0x0b, 0x21, 0xea, 0xbd, 0x85, 0xc4, 0xf7, 0x20, 0x9d,
	0x29, 0x1f, 0xbc, 0xe8, 0x29, 0xc4, 0x58, 0x01, 0xd9, 0xac, 0xf2, 0xe1, 0xdf, 0xe7, 0x63, 0x0f,
	0x42, 0x36, 0x57, 0x67, 0x05, 0x56, 0x29, 0xcc, 0x8d, 0x40, 0xff, 0x0e, 0x20, 0x3a, 0x2f, 0xae,
	0x74, 0x15, 0x7b, 0x07, 0xcf, 0x71, 0x58, 0x69, 0x1c, 0xff, 0xa1, 0xc6, 0x09, 0xc6, 0x8d, 0xb3,
	0x12, 0xd2, 0xe4, 0x7e, 0x48, 0x23, 0x82, 0xd3, 0x15, 0x82, 0xbb, 0x06, 0x0a, 0xd7, 0x35, 0x10,
	0x8c, 0x1a, 0xc8, 0xa5, 0x35, 0xda, 0x9e, 0xd6, 0xf8, 0x69, 0xb4, 0x4e, 0xb7, 0xa7, 0x35, 0x79,
	0x14, 0xad, 0x5f, 0x43, 0x8c, 0x94, 0x3c, 0x86, 0x56, 0xfa, 0x0a, 0xa2, 0xb7, 0xd7, 0x6a, 0x23,
	0x7f, 0x74, 0x06, 0x31, 0xda, 0x65, 0xe3, 0xcc, 0x99, 0x37, 0x9a, 0xb3, 0x47, 0x5d, 0xf2, 0xae,
	0xbd, 0xdb, 0x7c, 0xc9, 0xbf, 0x3e, 0xc4, 0xe8, 0x20, 0x1b, 0x9d, 0xf0, 0x65, 0x37, 0x76, 0xe8,
	0xb5, 0x61, 0x22, 0x07, 0xaf, 0x11, 0x7f, 0xfe, 0xf6, 0xfc, 0x05, 0x4f, 0xe3, 0x6f, 0xb2, 0x3d,
	0x7f, 0xe1, 0x63, 0xf8, 0x23, 0xdf, 0xc0, 0x74, 0x5e, 0x97, 0x25, 0xaf, 0x94, 0xc4, 0xf5, 0x97,
	0x9e, 0x3c, 0x1f, 0x10, 0x33, 0x63, 0xc9, 0x7b, 0x17, 0x5a, 0xc0, 0xb4, 0xcb, 0x51, 0x4f, 0x5b,
	0xc1, 0x1b, 0xd6, 0x2a, 0x1c, 0x28, 0xcf, 0x4c, 0xdb, 0xa0, 0xd1, 0x14, 0xd6, 0xad, 0x58, 0x08,
	0xc3, 0xd2, 0x6e, 0x6e, 0x25, 0x4b, 0xa1, 0x12, 0x15, 0x43, 0x0a, 0x03, 0x34, 0xba, 0x2a, 0x7a,
	0x0a, 0xa9, 0x53, 0x16, 0xcd, 0xa3, 0x54, 0x75, 0xdb, 0xdd, 0x61, 0x04, 0x3d, 0x90, 0x98, 0xb9,
	0x33, 0xeb, 0x83, 0x82, 0x7e, 0x01, 0x49, 0x5f, 0xa2, 0xf5, 0x07, 0xd0, 0x63, 0x48, 0xfa, 0x92,
	0x10, 0x0a, 0xbb, 0x5d, 0xda, 0x4e, 0x3a, 0x23, 0x1d, 0xfd, 0xcb, 0x83, 0x68, 0x56, 0x6e, 0xee,
	0x5f, 0x9d, 0xf1, 0x52, 0xf2, 0xf6, 0xac, 0xc0, 0x78, 0xc2, 0xdc, 0x4a, 0xba, 0x52, 0x2d, 0x9f,
	0x73, 0x71, 0x83, 0xb6, 0x09, 0xda, 0x1c, 0x8d, 0xde, 0x4b, 0xf3, 0xba, 0x52, 0xbc, 0x52, 0xdd,
	0x5e, 0xb2, 0x22, 0x3e, 0x8f, 0x3a, 0x9c, 0xd0, 0x3e, 0x8f, 0x3a, 0x8c, 0x19, 0xc4, 0x18, 0xc5,
	0x07, 0x4d, 0x49, 0x0d, 0xb1, 0x65, 0xd7, 0x89, 0xda, 0x7b, 0x20, 0x6a, 0xff, 0x09, 0x51, 0x4f,
	0x9c, 0xa8, 0x7f, 0x84, 0xe8, 0x82, 0x2d, 0x6c, 0xed, 0xcc, 0x23, 0xed, 0x3d, 0xf0, 0x48, 0xaf,
	0x09, 0xf9, 0x35, 0xc4, 0x78, 0xc2, 0x03, 0x79, 0xdb, 0x35, 0xec, 0xf7, 0x6b, 0x98, 0xbe, 0x01,
	0x38, 0x2d, 0x8a, 0x0b, 0xb6, 0x90, 0xfa, 0x6a, 0x1d, 0x18, 0x5b, 0x68, 0x54, 0x80, 0x81, 0xb1,
	0x85, 0xdc, 0x44, 0x1a, 0xfd, 0x1c, 0xd2, 0x1e, 0x29, 0x1b, 0x7d, 0x74, 0xb5, 0x2c, 0xed, 0x7d,
	0xfa, 0x93, 0x7e, 0x09, 0xbb, 0x39, 0x37, 0x93, 0x51, 0xe8, 0xc3, 0x37, 0xd4, 0x91, 0xfe, 0x00,
	0x1f, 0x39, 0x7e, 0xa3, 0xe8, 0xfd, 0x51, 0xf4, 0x4e, 0x53, 0x05, 0x7d, 0x53, 0x9d, 0xfc, 0x13,
	0x40, 0x7a, 0x6a, 0xdb, 0xf0, 0xb7, 0xf6, 0x86, 0x7c, 0x8b, 0x0f, 0xe9, 0xb5, 0x90, 0xef, 0xc9,
	0xb3, 0x61, 0x54, 0xcd, 0xdf, 0xc5, 0xfe, 0xf3, 0x15, 0x8d, 0x6c, 0xe8, 0x0e, 0x39, 0x86, 0xe8,
	0xbc, 0x2e, 0xc4, 0xd5, 0x9d, 0x0b, 0x30, 0x0f, 0xa9, 0x0b, 0xb0, 0x7b, 0xdc, 0x00, 0xde, 0xf2,
	0x6b, 0xae, 0xb8, 0x0b, 0x30, 0x9b, 0xdb, 0x05, 0xd8, 0x5d, 0x4d, 0x77, 0xc8, 0x11, 0x84, 0xef,
	0x96, 0xbc, 0x1d, 0x5d, 0x60, 0x96, 0xb0, 0xeb, 0x6f, 0xb7, 0x2e, 0xdd, 0xd1, 0x39, 0x74, 0xdd,
	0xe7, 0x20, 0xcc, 0x6c, 0xb9, 0x08, 0xdb, 0xe7, 0x06, 0xf1, 0x33, 0xaf, 0x34, 0x1b, 0x2e, 0xc2,
	0x74, 0x94, 0x8b, 0xb0, 0x1d, 0x42, 0x77, 0xc8, 0x1b, 0x88, 0x2d, 0x7f, 0x64, 0x6f, 0xb0, 0x0f,
	0xcd, 0xb0, 0xff, 0x62, 0x8d, 0x16, 0x91, 0x33, 0xf8, 0xb8, 0x27, 0x0c, 0x17, 0x12, 0x79, 0x39,
	0xb8, 0xba, 0x94, 0xef, 0x7f, 0xba, 0x56, 0xaf, 0x0f, 0xb9, 0x8c, 0xf0, 0xbf, 0xf7, 0xf5, 0xff,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xea, 0xf9, 0xa4, 0xd7, 0x0f, 0x0b, 0x00, 0x00,
}
