// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/activity.proto

package activity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Activity service

type ActivityService interface {
	Publish(ctx context.Context, in *PubReq, opts ...client.CallOption) (*PubResp, error)
}

type activityService struct {
	c    client.Client
	name string
}

func NewActivityService(name string, c client.Client) ActivityService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "activity"
	}
	return &activityService{
		c:    c,
		name: name,
	}
}

func (c *activityService) Publish(ctx context.Context, in *PubReq, opts ...client.CallOption) (*PubResp, error) {
	req := c.c.NewRequest(c.name, "Activity.Publish", in)
	out := new(PubResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Activity service

type ActivityHandler interface {
	Publish(context.Context, *PubReq, *PubResp) error
}

func RegisterActivityHandler(s server.Server, hdlr ActivityHandler, opts ...server.HandlerOption) error {
	type activity interface {
		Publish(ctx context.Context, in *PubReq, out *PubResp) error
	}
	type Activity struct {
		activity
	}
	h := &activityHandler{hdlr}
	return s.Handle(s.NewHandler(&Activity{h}, opts...))
}

type activityHandler struct {
	ActivityHandler
}

func (h *activityHandler) Publish(ctx context.Context, in *PubReq, out *PubResp) error {
	return h.ActivityHandler.Publish(ctx, in, out)
}
