// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/activity.proto

package activity

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PubReq struct {
	//int32 actid = 1;
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	CreateTime           string   `protobuf:"bytes,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	EndTime              string   `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Tag                  []string `protobuf:"bytes,7,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubReq) Reset()         { *m = PubReq{} }
func (m *PubReq) String() string { return proto.CompactTextString(m) }
func (*PubReq) ProtoMessage()    {}
func (*PubReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{0}
}

func (m *PubReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubReq.Unmarshal(m, b)
}
func (m *PubReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubReq.Marshal(b, m, deterministic)
}
func (m *PubReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubReq.Merge(m, src)
}
func (m *PubReq) XXX_Size() int {
	return xxx_messageInfo_PubReq.Size(m)
}
func (m *PubReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PubReq.DiscardUnknown(m)
}

var xxx_messageInfo_PubReq proto.InternalMessageInfo

func (m *PubReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PubReq) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *PubReq) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *PubReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PubReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PubReq) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

type PubResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Actid                int32    `protobuf:"varint,3,opt,name=actid,proto3" json:"actid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubResp) Reset()         { *m = PubResp{} }
func (m *PubResp) String() string { return proto.CompactTextString(m) }
func (*PubResp) ProtoMessage()    {}
func (*PubResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{1}
}

func (m *PubResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubResp.Unmarshal(m, b)
}
func (m *PubResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubResp.Marshal(b, m, deterministic)
}
func (m *PubResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubResp.Merge(m, src)
}
func (m *PubResp) XXX_Size() int {
	return xxx_messageInfo_PubResp.Size(m)
}
func (m *PubResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PubResp.DiscardUnknown(m)
}

var xxx_messageInfo_PubResp proto.InternalMessageInfo

func (m *PubResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PubResp) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PubResp) GetActid() int32 {
	if m != nil {
		return m.Actid
	}
	return 0
}

type MdfReq struct {
	Actid                int32    `protobuf:"varint,1,opt,name=actid,proto3" json:"actid,omitempty"`
	CreateTime           string   `protobuf:"bytes,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	EndTime              string   `protobuf:"bytes,3,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tag                  []string `protobuf:"bytes,5,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MdfReq) Reset()         { *m = MdfReq{} }
func (m *MdfReq) String() string { return proto.CompactTextString(m) }
func (*MdfReq) ProtoMessage()    {}
func (*MdfReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{2}
}

func (m *MdfReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MdfReq.Unmarshal(m, b)
}
func (m *MdfReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MdfReq.Marshal(b, m, deterministic)
}
func (m *MdfReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MdfReq.Merge(m, src)
}
func (m *MdfReq) XXX_Size() int {
	return xxx_messageInfo_MdfReq.Size(m)
}
func (m *MdfReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MdfReq.DiscardUnknown(m)
}

var xxx_messageInfo_MdfReq proto.InternalMessageInfo

func (m *MdfReq) GetActid() int32 {
	if m != nil {
		return m.Actid
	}
	return 0
}

func (m *MdfReq) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *MdfReq) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *MdfReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MdfReq) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

type MdfResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MdfResp) Reset()         { *m = MdfResp{} }
func (m *MdfResp) String() string { return proto.CompactTextString(m) }
func (*MdfResp) ProtoMessage()    {}
func (*MdfResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{3}
}

func (m *MdfResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MdfResp.Unmarshal(m, b)
}
func (m *MdfResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MdfResp.Marshal(b, m, deterministic)
}
func (m *MdfResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MdfResp.Merge(m, src)
}
func (m *MdfResp) XXX_Size() int {
	return xxx_messageInfo_MdfResp.Size(m)
}
func (m *MdfResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MdfResp.DiscardUnknown(m)
}

var xxx_messageInfo_MdfResp proto.InternalMessageInfo

func (m *MdfResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MdfResp) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type DltReq struct {
	Actid                int32    `protobuf:"varint,1,opt,name=actid,proto3" json:"actid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DltReq) Reset()         { *m = DltReq{} }
func (m *DltReq) String() string { return proto.CompactTextString(m) }
func (*DltReq) ProtoMessage()    {}
func (*DltReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{4}
}

func (m *DltReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DltReq.Unmarshal(m, b)
}
func (m *DltReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DltReq.Marshal(b, m, deterministic)
}
func (m *DltReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DltReq.Merge(m, src)
}
func (m *DltReq) XXX_Size() int {
	return xxx_messageInfo_DltReq.Size(m)
}
func (m *DltReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DltReq.DiscardUnknown(m)
}

var xxx_messageInfo_DltReq proto.InternalMessageInfo

func (m *DltReq) GetActid() int32 {
	if m != nil {
		return m.Actid
	}
	return 0
}

type DltResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DltResp) Reset()         { *m = DltResp{} }
func (m *DltResp) String() string { return proto.CompactTextString(m) }
func (*DltResp) ProtoMessage()    {}
func (*DltResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{5}
}

func (m *DltResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DltResp.Unmarshal(m, b)
}
func (m *DltResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DltResp.Marshal(b, m, deterministic)
}
func (m *DltResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DltResp.Merge(m, src)
}
func (m *DltResp) XXX_Size() int {
	return xxx_messageInfo_DltResp.Size(m)
}
func (m *DltResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DltResp.DiscardUnknown(m)
}

var xxx_messageInfo_DltResp proto.InternalMessageInfo

func (m *DltResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DltResp) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type QryReq struct {
	Actid                int32    `protobuf:"varint,1,opt,name=actid,proto3" json:"actid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QryReq) Reset()         { *m = QryReq{} }
func (m *QryReq) String() string { return proto.CompactTextString(m) }
func (*QryReq) ProtoMessage()    {}
func (*QryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{6}
}

func (m *QryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QryReq.Unmarshal(m, b)
}
func (m *QryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QryReq.Marshal(b, m, deterministic)
}
func (m *QryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QryReq.Merge(m, src)
}
func (m *QryReq) XXX_Size() int {
	return xxx_messageInfo_QryReq.Size(m)
}
func (m *QryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QryReq.DiscardUnknown(m)
}

var xxx_messageInfo_QryReq proto.InternalMessageInfo

func (m *QryReq) GetActid() int32 {
	if m != nil {
		return m.Actid
	}
	return 0
}

type QryResp struct {
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	CreateTime           string   `protobuf:"bytes,3,opt,name=createTime,proto3" json:"createTime,omitempty"`
	EndTime              string   `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Tag                  []string `protobuf:"bytes,7,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QryResp) Reset()         { *m = QryResp{} }
func (m *QryResp) String() string { return proto.CompactTextString(m) }
func (*QryResp) ProtoMessage()    {}
func (*QryResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_970235c7b4e4341e, []int{7}
}

func (m *QryResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QryResp.Unmarshal(m, b)
}
func (m *QryResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QryResp.Marshal(b, m, deterministic)
}
func (m *QryResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QryResp.Merge(m, src)
}
func (m *QryResp) XXX_Size() int {
	return xxx_messageInfo_QryResp.Size(m)
}
func (m *QryResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QryResp.DiscardUnknown(m)
}

var xxx_messageInfo_QryResp proto.InternalMessageInfo

func (m *QryResp) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *QryResp) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *QryResp) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *QryResp) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *QryResp) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *QryResp) GetTag() []string {
	if m != nil {
		return m.Tag
	}
	return nil
}

func init() {
	proto.RegisterType((*PubReq)(nil), "activity.PubReq")
	proto.RegisterType((*PubResp)(nil), "activity.PubResp")
	proto.RegisterType((*MdfReq)(nil), "activity.MdfReq")
	proto.RegisterType((*MdfResp)(nil), "activity.MdfResp")
	proto.RegisterType((*DltReq)(nil), "activity.DltReq")
	proto.RegisterType((*DltResp)(nil), "activity.DltResp")
	proto.RegisterType((*QryReq)(nil), "activity.QryReq")
	proto.RegisterType((*QryResp)(nil), "activity.QryResp")
}

func init() { proto.RegisterFile("proto/activity.proto", fileDescriptor_970235c7b4e4341e) }

var fileDescriptor_970235c7b4e4341e = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x93, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0xc7, 0x59, 0x4a, 0xb7, 0x32, 0x5c, 0x70, 0x43, 0xcc, 0xc6, 0x03, 0x69, 0xf6, 0xc4, 0x09,
	0x8c, 0x3e, 0x81, 0x91, 0x2b, 0x89, 0x54, 0x2f, 0x1e, 0x0b, 0x5d, 0x74, 0x93, 0x4a, 0x6b, 0x77,
	0x21, 0xe9, 0x3b, 0xf8, 0x10, 0xfa, 0x48, 0xbe, 0x91, 0xe9, 0x6c, 0xc1, 0xa5, 0x06, 0x2f, 0x5c,
	0xbc, 0xed, 0x7f, 0x3e, 0x76, 0xf6, 0xb7, 0x33, 0x03, 0x83, 0xbc, 0xc8, 0x4c, 0x36, 0x89, 0x97,
	0x46, 0x6d, 0x95, 0x29, 0xc7, 0x28, 0xd9, 0xd9, 0x4e, 0x8b, 0x0f, 0x02, 0xf4, 0x7e, 0xb3, 0x88,
	0xe4, 0x1b, 0x63, 0xd0, 0x31, 0x65, 0x2e, 0x79, 0x3b, 0x24, 0xa3, 0x6e, 0x84, 0x67, 0x36, 0x04,
	0x58, 0x16, 0x32, 0x36, 0xf2, 0x51, 0xbd, 0x4a, 0xee, 0xa1, 0xc7, 0xb1, 0x30, 0x0e, 0x81, 0x5c,
	0x27, 0xe8, 0xec, 0xa0, 0x73, 0x27, 0xd9, 0x00, 0x7c, 0xa3, 0x4c, 0x2a, 0xb9, 0x8f, 0x76, 0x2b,
	0x58, 0x08, 0xbd, 0x44, 0xea, 0x65, 0xa1, 0x72, 0xa3, 0xb2, 0x35, 0xa7, 0xe8, 0x73, 0x4d, 0xac,
	0x0f, 0x9e, 0x89, 0x9f, 0x79, 0x10, 0x7a, 0xa3, 0x6e, 0x54, 0x1d, 0xc5, 0x13, 0x04, 0xf8, 0x42,
	0x9d, 0xb3, 0x0b, 0xa0, 0xda, 0xc4, 0x66, 0xa3, 0x39, 0x09, 0xc9, 0xc8, 0x8f, 0x6a, 0xd5, 0xbc,
	0xb6, 0xfd, 0xfb, 0xda, 0x01, 0xf8, 0x15, 0x73, 0x82, 0x0c, 0x7e, 0x64, 0x85, 0x78, 0x27, 0x40,
	0x67, 0xc9, 0xaa, 0xa2, 0xdf, 0x07, 0x10, 0x27, 0xa0, 0xc1, 0xdf, 0xfe, 0x8b, 0xdf, 0x3b, 0xe4,
	0x6f, 0x3c, 0xa9, 0x73, 0x94, 0xd4, 0xff, 0x21, 0xbd, 0x83, 0x00, 0x5f, 0x73, 0x0a, 0xa9, 0x18,
	0x02, 0x9d, 0xa6, 0xe6, 0x28, 0x52, 0x55, 0x04, 0xfd, 0xa7, 0x16, 0x99, 0x17, 0xe5, 0xf1, 0x22,
	0x9f, 0x04, 0x02, 0x0c, 0xd0, 0xf9, 0x7f, 0x9d, 0xab, 0xeb, 0x2f, 0x02, 0xbd, 0xdb, 0x7a, 0x0f,
	0x1e, 0x8a, 0x2d, 0xbb, 0xc2, 0x39, 0x4b, 0x95, 0x7e, 0x61, 0xfd, 0xf1, 0x7e, 0x61, 0xec, 0x72,
	0x5c, 0x9e, 0x37, 0x2c, 0x3a, 0x17, 0x2d, 0x36, 0x01, 0x3a, 0xcb, 0x12, 0xb5, 0x2a, 0xdd, 0x04,
	0x3b, 0x4f, 0x6e, 0x42, 0xdd, 0x53, 0x9b, 0x30, 0x95, 0xa9, 0x34, 0xd2, 0x4d, 0xb0, 0xdd, 0x72,
	0x13, 0xea, 0xfe, 0x88, 0x16, 0x1b, 0x83, 0x3f, 0xdf, 0xc8, 0xe2, 0xa0, 0x80, 0xfd, 0x78, 0x37,
	0xbe, 0xfe, 0x69, 0xd1, 0x5a, 0x50, 0xdc, 0xef, 0x9b, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf8,
	0xf9, 0xd7, 0x49, 0xf7, 0x03, 0x00, 0x00,
}
