############################################################
# Dockerfile to build login container images
############################################################
# Set the base image to Ubuntu
FROM ubuntu
# Add app to the image
ADD ./user /home/app/bin
# Run APP
CMD [ "/home/app/bin" ] 
