############################################################
# Dockerfile to build gateway container images
############################################################
# Set the base image to Ubuntu
FROM ubuntu
# Add app to the image
ADD ./main /home/app/bin
# Run APP
CMD [ "/home/app/bin/main" ] 