// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package go_micro_srv_login

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccessResp struct {
	AccessToken          string   `protobuf:"bytes,11,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessResp) Reset()         { *m = AccessResp{} }
func (m *AccessResp) String() string { return proto.CompactTextString(m) }
func (*AccessResp) ProtoMessage()    {}
func (*AccessResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *AccessResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessResp.Unmarshal(m, b)
}
func (m *AccessResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessResp.Marshal(b, m, deterministic)
}
func (m *AccessResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessResp.Merge(m, src)
}
func (m *AccessResp) XXX_Size() int {
	return xxx_messageInfo_AccessResp.Size(m)
}
func (m *AccessResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessResp.DiscardUnknown(m)
}

var xxx_messageInfo_AccessResp proto.InternalMessageInfo

func (m *AccessResp) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type CodeReq struct {
	RedirectUri          string   `protobuf:"bytes,9,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	Code                 string   `protobuf:"bytes,10,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeReq) Reset()         { *m = CodeReq{} }
func (m *CodeReq) String() string { return proto.CompactTextString(m) }
func (*CodeReq) ProtoMessage()    {}
func (*CodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *CodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeReq.Unmarshal(m, b)
}
func (m *CodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeReq.Marshal(b, m, deterministic)
}
func (m *CodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeReq.Merge(m, src)
}
func (m *CodeReq) XXX_Size() int {
	return xxx_messageInfo_CodeReq.Size(m)
}
func (m *CodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_CodeReq proto.InternalMessageInfo

func (m *CodeReq) GetRedirectUri() string {
	if m != nil {
		return m.RedirectUri
	}
	return ""
}

func (m *CodeReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type AuthReq struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthReq) Reset()         { *m = AuthReq{} }
func (m *AuthReq) String() string { return proto.CompactTextString(m) }
func (*AuthReq) ProtoMessage()    {}
func (*AuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *AuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthReq.Unmarshal(m, b)
}
func (m *AuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthReq.Marshal(b, m, deterministic)
}
func (m *AuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthReq.Merge(m, src)
}
func (m *AuthReq) XXX_Size() int {
	return xxx_messageInfo_AuthReq.Size(m)
}
func (m *AuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthReq proto.InternalMessageInfo

func (m *AuthReq) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type AuthResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username             string   `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Admin                bool     `protobuf:"varint,3,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResp) Reset()         { *m = AuthResp{} }
func (m *AuthResp) String() string { return proto.CompactTextString(m) }
func (*AuthResp) ProtoMessage()    {}
func (*AuthResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *AuthResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResp.Unmarshal(m, b)
}
func (m *AuthResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResp.Marshal(b, m, deterministic)
}
func (m *AuthResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResp.Merge(m, src)
}
func (m *AuthResp) XXX_Size() int {
	return xxx_messageInfo_AuthResp.Size(m)
}
func (m *AuthResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResp.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResp proto.InternalMessageInfo

func (m *AuthResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AuthResp) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AuthResp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthResp) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

type LJReq struct {
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LJReq) Reset()         { *m = LJReq{} }
func (m *LJReq) String() string { return proto.CompactTextString(m) }
func (*LJReq) ProtoMessage()    {}
func (*LJReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{4}
}

func (m *LJReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LJReq.Unmarshal(m, b)
}
func (m *LJReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LJReq.Marshal(b, m, deterministic)
}
func (m *LJReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LJReq.Merge(m, src)
}
func (m *LJReq) XXX_Size() int {
	return xxx_messageInfo_LJReq.Size(m)
}
func (m *LJReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LJReq.DiscardUnknown(m)
}

var xxx_messageInfo_LJReq proto.InternalMessageInfo

func (m *LJReq) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type TokenResp struct {
	Status int32 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	// uncaught error = -1, success = 0, incorrect = 1, access_token expired = 11, invalid jaccount = 12, need jaccount = 21 (weixin), need fill form = 22
	JwtToken             string   `protobuf:"bytes,5,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenResp) Reset()         { *m = TokenResp{} }
func (m *TokenResp) String() string { return proto.CompactTextString(m) }
func (*TokenResp) ProtoMessage()    {}
func (*TokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{5}
}

func (m *TokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResp.Unmarshal(m, b)
}
func (m *TokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResp.Marshal(b, m, deterministic)
}
func (m *TokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResp.Merge(m, src)
}
func (m *TokenResp) XXX_Size() int {
	return xxx_messageInfo_TokenResp.Size(m)
}
func (m *TokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResp proto.InternalMessageInfo

func (m *TokenResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *TokenResp) GetJwtToken() string {
	if m != nil {
		return m.JwtToken
	}
	return ""
}

type UPReq struct {
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UPReq) Reset()         { *m = UPReq{} }
func (m *UPReq) String() string { return proto.CompactTextString(m) }
func (*UPReq) ProtoMessage()    {}
func (*UPReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{6}
}

func (m *UPReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UPReq.Unmarshal(m, b)
}
func (m *UPReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UPReq.Marshal(b, m, deterministic)
}
func (m *UPReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UPReq.Merge(m, src)
}
func (m *UPReq) XXX_Size() int {
	return xxx_messageInfo_UPReq.Size(m)
}
func (m *UPReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UPReq.DiscardUnknown(m)
}

var xxx_messageInfo_UPReq proto.InternalMessageInfo

func (m *UPReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UPReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type WxReq struct {
	Code                 string   `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WxReq) Reset()         { *m = WxReq{} }
func (m *WxReq) String() string { return proto.CompactTextString(m) }
func (*WxReq) ProtoMessage()    {}
func (*WxReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{7}
}

func (m *WxReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxReq.Unmarshal(m, b)
}
func (m *WxReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxReq.Marshal(b, m, deterministic)
}
func (m *WxReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxReq.Merge(m, src)
}
func (m *WxReq) XXX_Size() int {
	return xxx_messageInfo_WxReq.Size(m)
}
func (m *WxReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WxReq.DiscardUnknown(m)
}

var xxx_messageInfo_WxReq proto.InternalMessageInfo

func (m *WxReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func init() {
	proto.RegisterType((*AccessResp)(nil), "go.micro.srv.login.AccessResp")
	proto.RegisterType((*CodeReq)(nil), "go.micro.srv.login.CodeReq")
	proto.RegisterType((*AuthReq)(nil), "go.micro.srv.login.AuthReq")
	proto.RegisterType((*AuthResp)(nil), "go.micro.srv.login.AuthResp")
	proto.RegisterType((*LJReq)(nil), "go.micro.srv.login.LJReq")
	proto.RegisterType((*TokenResp)(nil), "go.micro.srv.login.TokenResp")
	proto.RegisterType((*UPReq)(nil), "go.micro.srv.login.UPReq")
	proto.RegisterType((*WxReq)(nil), "go.micro.srv.login.WxReq")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x5f, 0x6f, 0xda, 0x30,
	0x14, 0xc5, 0xf9, 0x67, 0x48, 0x2e, 0xd3, 0x36, 0x59, 0xd3, 0x96, 0x25, 0xdb, 0xc4, 0xfc, 0x84,
	0xf6, 0x90, 0x49, 0xdb, 0x07, 0xd8, 0x28, 0x0f, 0xa8, 0x88, 0xaa, 0x28, 0x2a, 0xe2, 0x11, 0xa5,
	0x89, 0x45, 0x43, 0x9b, 0x38, 0xb5, 0x9d, 0x86, 0x7e, 0xf9, 0xaa, 0xb2, 0x13, 0x42, 0xa1, 0xa9,
	0xaa, 0xbe, 0xdd, 0xe3, 0x63, 0x7e, 0xdc, 0x7b, 0x6e, 0x0c, 0xfd, 0x1b, 0xb6, 0x8e, 0x12, 0x37,
	0xe5, 0x4c, 0x32, 0x8c, 0xd7, 0xcc, 0x8d, 0xa3, 0x80, 0x33, 0x57, 0xf0, 0x3b, 0x57, 0x3b, 0xe4,
	0x37, 0xc0, 0x28, 0x08, 0xa8, 0x10, 0x1e, 0x15, 0x29, 0xfe, 0x09, 0xef, 0x7c, 0xad, 0x56, 0x92,
	0x5d, 0xd3, 0xc4, 0xea, 0x0f, 0x9a, 0x43, 0xd3, 0xeb, 0x17, 0x67, 0x17, 0xea, 0x88, 0xfc, 0x87,
	0xde, 0x98, 0x85, 0xd4, 0xa3, 0xb7, 0xea, 0x36, 0xa7, 0x61, 0xc4, 0x69, 0x20, 0x57, 0x19, 0x8f,
	0x2c, 0xb3, 0xb8, 0xbd, 0x3b, 0x5b, 0xf0, 0x08, 0x63, 0xe8, 0x04, 0x2c, 0xa4, 0x16, 0x68, 0x4b,
	0xd7, 0xc4, 0x81, 0xde, 0x28, 0x93, 0x57, 0x8a, 0xf0, 0x11, 0xda, 0x9b, 0x5c, 0x5a, 0x4d, 0xed,
	0xaa, 0x92, 0xc4, 0x60, 0x14, 0xa6, 0x48, 0xf1, 0x67, 0xe8, 0x0a, 0xe9, 0xcb, 0x4c, 0xe8, 0x0b,
	0xc8, 0x2b, 0x15, 0xfe, 0x02, 0xbd, 0x4c, 0x50, 0xbe, 0x8a, 0x42, 0xab, 0x55, 0x18, 0x4a, 0x9e,
	0x86, 0xd8, 0x06, 0x43, 0x55, 0x89, 0x1f, 0x53, 0xab, 0xab, 0x99, 0x95, 0xc6, 0x9f, 0x00, 0xf9,
	0x61, 0x1c, 0x25, 0x56, 0x7b, 0xd0, 0x1c, 0x1a, 0x5e, 0x21, 0xc8, 0x2f, 0x40, 0xb3, 0x69, 0x39,
	0xcb, 0xc1, 0xe4, 0xad, 0xba, 0xc9, 0x4d, 0x5d, 0x1c, 0xf5, 0xd6, 0x39, 0xe8, 0xcd, 0x01, 0x73,
	0x93, 0xcb, 0x12, 0x82, 0x8a, 0x1e, 0x36, 0xb9, 0x2c, 0x08, 0xff, 0x00, 0x2d, 0xe6, 0xea, 0xdf,
	0x9e, 0x36, 0xda, 0x3e, 0x6a, 0xd4, 0x06, 0x23, 0xf5, 0x85, 0xc8, 0x19, 0x0f, 0x35, 0xdb, 0xf4,
	0x2a, 0x4d, 0x1c, 0x40, 0xcb, 0xad, 0x02, 0xec, 0x72, 0x45, 0xfb, 0x5c, 0xff, 0x3c, 0xb4, 0x00,
	0xcd, 0xd4, 0x52, 0xf1, 0x18, 0x3a, 0x2a, 0x44, 0xec, 0xb8, 0xcf, 0x37, 0xee, 0x96, 0xd9, 0xdb,
	0xdf, 0x5e, 0x36, 0x45, 0x4a, 0x1a, 0xf8, 0x0c, 0x3e, 0x68, 0xda, 0xc9, 0xfd, 0xd4, 0x0f, 0x02,
	0x96, 0x25, 0x12, 0x7f, 0xad, 0xfb, 0x89, 0xce, 0xcf, 0xfe, 0x5e, 0x67, 0x55, 0x71, 0x91, 0x06,
	0x9e, 0x80, 0x59, 0xe2, 0x16, 0xf3, 0x7a, 0x90, 0x8e, 0xe6, 0x2d, 0xa0, 0xe5, 0xb6, 0x1e, 0xa4,
	0x23, 0x7a, 0x1d, 0x74, 0x0e, 0xef, 0x27, 0x54, 0x8e, 0xf6, 0x1b, 0xae, 0xcf, 0xab, 0xfc, 0xda,
	0xed, 0x1f, 0xb5, 0x79, 0x55, 0x6f, 0x87, 0x34, 0x2e, 0xbb, 0xfa, 0x99, 0xfd, 0x7d, 0x0c, 0x00,
	0x00, 0xff, 0xff, 0xdd, 0x46, 0x92, 0xe1, 0x75, 0x03, 0x00, 0x00,
}
