---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-user
  namespace: app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-demo
          image: jing855/user
          ports:
            - containerPort: 5000
          args: [
              "--net=host"
          ]
---
apiVersion: v1
kind: Service
metadata:
  name: app-user-svc
  namespace: app
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: web
    nodePort: 30254
  selector:
    app: user
  type: NodePort

