// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package go_micro_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateReq struct {
	Id                   int32    `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReq) Reset()         { *m = UpdateReq{} }
func (m *UpdateReq) String() string { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()    {}
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReq.Unmarshal(m, b)
}
func (m *UpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReq.Marshal(b, m, deterministic)
}
func (m *UpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReq.Merge(m, src)
}
func (m *UpdateReq) XXX_Size() int {
	return xxx_messageInfo_UpdateReq.Size(m)
}
func (m *UpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReq proto.InternalMessageInfo

func (m *UpdateReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpdateReq) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *UpdateReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type UpdateResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResp) Reset()         { *m = UpdateResp{} }
func (m *UpdateResp) String() string { return proto.CompactTextString(m) }
func (*UpdateResp) ProtoMessage()    {}
func (*UpdateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UpdateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResp.Unmarshal(m, b)
}
func (m *UpdateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResp.Marshal(b, m, deterministic)
}
func (m *UpdateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResp.Merge(m, src)
}
func (m *UpdateResp) XXX_Size() int {
	return xxx_messageInfo_UpdateResp.Size(m)
}
func (m *UpdateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResp.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResp proto.InternalMessageInfo

func (m *UpdateResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type RegReq struct {
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Nickname             string   `protobuf:"bytes,7,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Jwt                  string   `protobuf:"bytes,8,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegReq) Reset()         { *m = RegReq{} }
func (m *RegReq) String() string { return proto.CompactTextString(m) }
func (*RegReq) ProtoMessage()    {}
func (*RegReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *RegReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegReq.Unmarshal(m, b)
}
func (m *RegReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegReq.Marshal(b, m, deterministic)
}
func (m *RegReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegReq.Merge(m, src)
}
func (m *RegReq) XXX_Size() int {
	return xxx_messageInfo_RegReq.Size(m)
}
func (m *RegReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegReq proto.InternalMessageInfo

func (m *RegReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegReq) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type RegResp struct {
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegResp) Reset()         { *m = RegResp{} }
func (m *RegResp) String() string { return proto.CompactTextString(m) }
func (*RegResp) ProtoMessage()    {}
func (*RegResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *RegResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegResp.Unmarshal(m, b)
}
func (m *RegResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegResp.Marshal(b, m, deterministic)
}
func (m *RegResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegResp.Merge(m, src)
}
func (m *RegResp) XXX_Size() int {
	return xxx_messageInfo_RegResp.Size(m)
}
func (m *RegResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegResp.DiscardUnknown(m)
}

var xxx_messageInfo_RegResp proto.InternalMessageInfo

func (m *RegResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type FindReq struct {
	Id                   int32    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindReq) Reset()         { *m = FindReq{} }
func (m *FindReq) String() string { return proto.CompactTextString(m) }
func (*FindReq) ProtoMessage()    {}
func (*FindReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *FindReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindReq.Unmarshal(m, b)
}
func (m *FindReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindReq.Marshal(b, m, deterministic)
}
func (m *FindReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindReq.Merge(m, src)
}
func (m *FindReq) XXX_Size() int {
	return xxx_messageInfo_FindReq.Size(m)
}
func (m *FindReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FindReq.DiscardUnknown(m)
}

var xxx_messageInfo_FindReq proto.InternalMessageInfo

func (m *FindReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FindResp struct {
	Gender               int32    `protobuf:"varint,1,opt,name=gender,proto3" json:"gender,omitempty"`
	Id                   int32    `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Nickname             string   `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Jaccount             string   `protobuf:"bytes,7,opt,name=jaccount,proto3" json:"jaccount,omitempty"`
	Signature            string   `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,9,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Birthday             string   `protobuf:"bytes,10,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Dormitory            string   `protobuf:"bytes,11,opt,name=dormitory,proto3" json:"dormitory,omitempty"`
	Major                string   `protobuf:"bytes,12,opt,name=major,proto3" json:"major,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindResp) Reset()         { *m = FindResp{} }
func (m *FindResp) String() string { return proto.CompactTextString(m) }
func (*FindResp) ProtoMessage()    {}
func (*FindResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *FindResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindResp.Unmarshal(m, b)
}
func (m *FindResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindResp.Marshal(b, m, deterministic)
}
func (m *FindResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindResp.Merge(m, src)
}
func (m *FindResp) XXX_Size() int {
	return xxx_messageInfo_FindResp.Size(m)
}
func (m *FindResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FindResp.DiscardUnknown(m)
}

var xxx_messageInfo_FindResp proto.InternalMessageInfo

func (m *FindResp) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *FindResp) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FindResp) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *FindResp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FindResp) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *FindResp) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *FindResp) GetJaccount() string {
	if m != nil {
		return m.Jaccount
	}
	return ""
}

func (m *FindResp) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *FindResp) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *FindResp) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *FindResp) GetDormitory() string {
	if m != nil {
		return m.Dormitory
	}
	return ""
}

func (m *FindResp) GetMajor() string {
	if m != nil {
		return m.Major
	}
	return ""
}

func init() {
	proto.RegisterType((*UpdateReq)(nil), "go.micro.srv.user.UpdateReq")
	proto.RegisterType((*UpdateResp)(nil), "go.micro.srv.user.UpdateResp")
	proto.RegisterType((*RegReq)(nil), "go.micro.srv.user.RegReq")
	proto.RegisterType((*RegResp)(nil), "go.micro.srv.user.RegResp")
	proto.RegisterType((*FindReq)(nil), "go.micro.srv.user.FindReq")
	proto.RegisterType((*FindResp)(nil), "go.micro.srv.user.FindResp")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x14, 0x24, 0xe9, 0x26, 0x4d, 0x1e, 0x08, 0x81, 0x85, 0x90, 0x37, 0xec, 0x4a, 0x4b, 0xc4, 0x61,
	0x4f, 0x39, 0xc0, 0x27, 0x20, 0xe0, 0x6e, 0xa9, 0x67, 0xe4, 0x8d, 0xad, 0xac, 0xbb, 0x9b, 0x38,
	0x3c, 0x3b, 0xbb, 0xea, 0x9d, 0x5f, 0xe3, 0x2b, 0xf8, 0x19, 0x64, 0xbb, 0x49, 0x9b, 0xd2, 0xf6,
	0xd6, 0x79, 0x63, 0x4f, 0x67, 0x9e, 0x27, 0x00, 0x83, 0x91, 0x58, 0xf5, 0xa8, 0xad, 0x26, 0x6f,
	0x1b, 0x5d, 0xb5, 0xaa, 0x46, 0x5d, 0x19, 0x7c, 0xaa, 0x1c, 0x51, 0x3e, 0x40, 0xbe, 0xea, 0x05,
	0xb7, 0x92, 0xc9, 0x5f, 0xe4, 0x35, 0xc4, 0x4a, 0x50, 0xb8, 0x89, 0x6e, 0x13, 0x16, 0x2b, 0x41,
	0xde, 0x41, 0xd2, 0xdf, 0xeb, 0x4e, 0xd2, 0xe8, 0x26, 0xba, 0xcd, 0x59, 0x00, 0xe4, 0x0a, 0x72,
	0xa3, 0x9a, 0x8e, 0xdb, 0x01, 0x25, 0x8d, 0x3d, 0xb3, 0x1b, 0x90, 0x02, 0xb2, 0x4e, 0xd5, 0x0f,
	0x1d, 0x6f, 0x25, 0x5d, 0x78, 0x72, 0xc2, 0xe5, 0x27, 0x80, 0xf1, 0xcf, 0x4c, 0x4f, 0xde, 0x43,
	0x6a, 0x2c, 0xb7, 0x83, 0xf1, 0xf2, 0x09, 0xdb, 0xa2, 0xf2, 0x77, 0x04, 0x29, 0x93, 0x8d, 0x33,
	0x54, 0x40, 0xe6, 0x5c, 0x7a, 0xb1, 0x8b, 0x20, 0x36, 0x62, 0xc7, 0xf5, 0xdc, 0x98, 0x67, 0x8d,
	0x82, 0x26, 0x81, 0x1b, 0xf1, 0xce, 0x78, 0xba, 0x6f, 0x7c, 0xdf, 0xda, 0x72, 0x6e, 0x8d, 0xbc,
	0x81, 0xc5, 0xfa, 0xd9, 0xd2, 0xcc, 0x8f, 0xdd, 0xcf, 0xf2, 0x23, 0x2c, 0xbd, 0x8b, 0x99, 0xd3,
	0x78, 0xe6, 0xf4, 0x12, 0x96, 0xdf, 0x55, 0x27, 0x76, 0xab, 0xcb, 0xc7, 0xd5, 0x95, 0x7f, 0x62,
	0xc8, 0x02, 0x17, 0xee, 0x37, 0xb2, 0x13, 0x12, 0xc7, 0xa4, 0x01, 0x6d, 0x2f, 0x2d, 0xa6, 0x7d,
	0xef, 0x47, 0x8a, 0x0f, 0x22, 0x9d, 0x5b, 0xc5, 0x14, 0x37, 0x39, 0x15, 0x37, 0x3d, 0x88, 0x5b,
	0x40, 0xb6, 0xe6, 0x75, 0xad, 0x87, 0xce, 0x8e, 0xab, 0x18, 0xf1, 0xfc, 0x7d, 0xb3, 0xc3, 0xf7,
	0xbd, 0x06, 0xe0, 0x4f, 0xdc, 0x72, 0xfc, 0x39, 0xe0, 0xa3, 0x0f, 0x9c, 0xb3, 0x3c, 0x4c, 0x56,
	0xf8, 0xe8, 0x84, 0xef, 0x14, 0xda, 0x7b, 0xc1, 0x37, 0xbe, 0x48, 0x39, 0x9b, 0xb0, 0x13, 0x16,
	0x1a, 0x5b, 0x65, 0x35, 0x6e, 0xe8, 0xcb, 0x70, 0x73, 0x1a, 0xb8, 0x10, 0x2d, 0x5f, 0x6b, 0xa4,
	0xaf, 0x42, 0x08, 0x0f, 0x3e, 0xff, 0x8d, 0xe0, 0x62, 0x65, 0x24, 0x92, 0x1f, 0x90, 0x86, 0xee,
	0x90, 0xab, 0xea, 0xbf, 0x1a, 0x57, 0x53, 0x87, 0x8b, 0xeb, 0x33, 0xac, 0xe9, 0xcb, 0x17, 0xe4,
	0x2b, 0x64, 0x4c, 0x36, 0xca, 0x58, 0x89, 0xe4, 0xf2, 0xc8, 0xe1, 0x50, 0xbd, 0xa2, 0x38, 0x45,
	0x79, 0x91, 0x6f, 0xe1, 0x75, 0xbd, 0xb3, 0x63, 0x27, 0xb7, 0xb5, 0x28, 0x3e, 0x9c, 0xe4, 0x9c,
	0xcc, 0x5d, 0xea, 0xbf, 0xcb, 0x2f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xdf, 0xe8, 0x08,
	0xa5, 0x03, 0x00, 0x00,
}
